---
apiVersion: v1
items:
- metadata:
    creationTimestamp: "2022-12-05T06:51:49Z"
    generateName: spire-agent-
    labels:
      app: spire-agent
      controller-revision-hash: 69b6bb49cf
      pod-template-generation: "1"
    name: spire-agent-ww4w7
    namespace: spire
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: DaemonSet
      name: spire-agent
      uid: b86e3aaf-e6b2-4636-9098-d82f8d744395
    resourceVersion: "736"
    uid: 2c61353c-85f1-4807-8eec-e1916ed7dc8d
  spec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchFields:
            - key: metadata.name
              operator: In
              values:
              - kind-2-control-plane
    containers:
    - args:
      - -config
      - /run/spire/config/agent.conf
      image: gcr.io/spiffe-io/spire-agent:1.2.3
      imagePullPolicy: IfNotPresent
      livenessProbe:
        exec:
          command:
          - /opt/spire/bin/spire-agent
          - healthcheck
          - -socketPath
          - /run/spire/sockets/agent.sock
        failureThreshold: 2
        initialDelaySeconds: 15
        periodSeconds: 60
        successThreshold: 1
        timeoutSeconds: 3
      name: spire-agent
      readinessProbe:
        exec:
          command:
          - /opt/spire/bin/spire-agent
          - healthcheck
          - -socketPath
          - /run/spire/sockets/agent.sock
          - --shallow
        failureThreshold: 3
        initialDelaySeconds: 5
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /run/spire/config
        name: spire-config
        readOnly: true
      - mountPath: /run/spire/bundle
        name: spire-bundle
      - mountPath: /run/spire/sockets
        name: spire-agent-socket
      - mountPath: /var/run/secrets/tokens
        name: spire-token
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-vq4rt
        readOnly: true
    dnsPolicy: ClusterFirstWithHostNet
    enableServiceLinks: true
    hostNetwork: true
    hostPID: true
    initContainers:
    - args:
      - -t
      - "30"
      - spire-server:8081
      image: gcr.io/spiffe-io/wait-for-it
      imagePullPolicy: IfNotPresent
      name: init
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-vq4rt
        readOnly: true
    - command:
      - sh
      - -c
      - t=0; until [ -f /run/spire/bundle/bundle.crt 2>&1 ] || [ $t -eq 60 ]; do t=`expr
        $t + 1`; sleep 1; done
      image: gcr.io/spiffe-io/wait-for-it
      imagePullPolicy: IfNotPresent
      name: init-bundle
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /run/spire/bundle
        name: spire-bundle
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-vq4rt
        readOnly: true
    nodeName: kind-2-control-plane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: spire-agent
    serviceAccountName: spire-agent
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/disk-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/memory-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/pid-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/unschedulable
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/network-unavailable
      operator: Exists
    volumes:
    - configMap:
        defaultMode: 420
        name: spire-agent
      name: spire-config
    - configMap:
        defaultMode: 420
        name: spire-bundle
      name: spire-bundle
    - hostPath:
        path: /run/spire/sockets
        type: DirectoryOrCreate
      name: spire-agent-socket
    - name: spire-token
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            audience: spire-server
            expirationSeconds: 7200
            path: spire-agent
    - name: kube-api-access-vq4rt
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-12-05T06:52:10Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-12-05T06:52:20Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-12-05T06:52:20Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-12-05T06:51:49Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://532f014d09704ba41d46d283d23d23544cb107ac9d2f5dd14fd7ae9b2322a2a2
      image: gcr.io/spiffe-io/spire-agent:1.2.3
      imageID: gcr.io/spiffe-io/spire-agent@sha256:e0791477303c598a77c08e63933c06805b773bf1b9c12f540cbd8682e631a510
      lastState: {}
      name: spire-agent
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-12-05T06:52:14Z"
    hostIP: 172.18.0.5
    initContainerStatuses:
    - containerID: containerd://f58c616df1e85f52a1991bfab4057325eeaff8470673de921810b7f3223bd662
      image: gcr.io/spiffe-io/wait-for-it:latest
      imageID: gcr.io/spiffe-io/wait-for-it@sha256:3facff26e582e57e3b994d3a3b95fc06475bb02a3dc6647ce6c91f4c3c2534b5
      lastState: {}
      name: init
      ready: true
      restartCount: 0
      state:
        terminated:
          containerID: containerd://f58c616df1e85f52a1991bfab4057325eeaff8470673de921810b7f3223bd662
          exitCode: 0
          finishedAt: "2022-12-05T06:52:09Z"
          reason: Completed
          startedAt: "2022-12-05T06:51:53Z"
    - containerID: containerd://d14a0a4c33ccb93392af75d7121873ee261a49ae33417f69013b665e3f0a1c3c
      image: gcr.io/spiffe-io/wait-for-it:latest
      imageID: gcr.io/spiffe-io/wait-for-it@sha256:3facff26e582e57e3b994d3a3b95fc06475bb02a3dc6647ce6c91f4c3c2534b5
      lastState: {}
      name: init-bundle
      ready: true
      restartCount: 0
      state:
        terminated:
          containerID: containerd://d14a0a4c33ccb93392af75d7121873ee261a49ae33417f69013b665e3f0a1c3c
          exitCode: 0
          finishedAt: "2022-12-05T06:52:09Z"
          reason: Completed
          startedAt: "2022-12-05T06:52:09Z"
    phase: Running
    podIP: 172.18.0.5
    podIPs:
    - ip: 172.18.0.5
    qosClass: BestEffort
    startTime: "2022-12-05T06:51:49Z"
- metadata:
    creationTimestamp: "2022-12-05T06:51:49Z"
    generateName: spire-server-
    labels:
      app: spire-server
      controller-revision-hash: spire-server-56cf88f8cf
      statefulset.kubernetes.io/pod-name: spire-server-0
    name: spire-server-0
    namespace: spire
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: StatefulSet
      name: spire-server
      uid: 2d513e88-b233-4510-ad7f-204ce555971a
    resourceVersion: "699"
    uid: d92d96a5-82c5-4cd5-a12d-f2425997fcd2
  spec:
    containers:
    - args:
      - -config
      - /run/spire/config/server.conf
      image: gcr.io/spiffe-io/spire-server:1.2.3
      imagePullPolicy: IfNotPresent
      lifecycle:
        postStart:
          exec:
            command:
            - sleep
            - "2"
      livenessProbe:
        exec:
          command:
          - /opt/spire/bin/spire-server
          - healthcheck
        failureThreshold: 2
        initialDelaySeconds: 15
        periodSeconds: 60
        successThreshold: 1
        timeoutSeconds: 3
      name: spire-server
      ports:
      - containerPort: 8081
        protocol: TCP
      readinessProbe:
        exec:
          command:
          - /opt/spire/bin/spire-server
          - healthcheck
          - --shallow
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /run/spire/config
        name: spire-config
        readOnly: true
      - mountPath: /tmp
        name: spire-registration-socket
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-ts4s6
        readOnly: true
    - args:
      - -config
      - /run/spire/config/k8s-workload-registrar.conf
      env:
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      image: gcr.io/spiffe-io/k8s-workload-registrar:1.2.3
      imagePullPolicy: IfNotPresent
      name: k8s-workload-registrar
      ports:
      - containerPort: 9443
        name: webhook
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /run/spire/config
        name: k8s-workload-registrar-config
        readOnly: true
      - mountPath: /run/spire/sockets
        name: spire-agent-socket
        readOnly: true
      - mountPath: /tmp
        name: spire-registration-socket
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-ts4s6
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostname: spire-server-0
    nodeName: kind-2-control-plane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: spire-server
    serviceAccountName: spire-server
    shareProcessNamespace: true
    subdomain: spire-server
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - configMap:
        defaultMode: 420
        name: spire-server
      name: spire-config
    - hostPath:
        path: /run/spire/sockets
        type: DirectoryOrCreate
      name: spire-agent-socket
    - configMap:
        defaultMode: 420
        name: k8s-workload-registrar
      name: k8s-workload-registrar-config
    - emptyDir: {}
      name: spire-registration-socket
    - name: kube-api-access-ts4s6
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-12-05T06:51:49Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-12-05T06:52:07Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-12-05T06:52:07Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-12-05T06:51:49Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://9852b6006fa9a17f461d6e9961e3a37de67e0b3c88717a9999a1d23b892291fe
      image: gcr.io/spiffe-io/k8s-workload-registrar:1.2.3
      imageID: gcr.io/spiffe-io/k8s-workload-registrar@sha256:46cc26598ce10c34c67e5ee1a71f212b77d8d5c52c5723a1cebed1bca3a8f9dd
      lastState: {}
      name: k8s-workload-registrar
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-12-05T06:52:06Z"
    - containerID: containerd://11ea56bd47a683fcd783f61060f91d193d26c6bdbcb91215a78438beffb87b7b
      image: gcr.io/spiffe-io/spire-server:1.2.3
      imageID: gcr.io/spiffe-io/spire-server@sha256:b02e6f3604513515fe131768be14a9c8b2e933ce56d2bdc91972bbf933e42dd6
      lastState: {}
      name: spire-server
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-12-05T06:51:59Z"
    hostIP: 172.18.0.5
    phase: Running
    podIP: 10.244.0.6
    podIPs:
    - ip: 10.244.0.6
    qosClass: BestEffort
    startTime: "2022-12-05T06:51:49Z"
kind: PodList
metadata:
  resourceVersion: "9750"
