---
apiVersion: apps/v1
items:
- metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"ubuntu"},"name":"ubuntu-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"ubuntu"}},"template":{"metadata":{"annotations":null,"labels":{"app":"ubuntu"}},"spec":{"containers":[{"command":["sleep","123456"],"image":"ubuntu","name":"ubuntu","securityContext":{"privileged":true}}]}}}}
    creationTimestamp: "2022-12-05T07:12:59Z"
    generation: 1
    labels:
      app: ubuntu
    name: ubuntu-deployment
    namespace: default
    resourceVersion: "2537"
    uid: 43178f7a-4067-4575-b14a-ffff5328ece0
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: ubuntu
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ubuntu
      spec:
        containers:
        - command:
          - sleep
          - "123456"
          image: ubuntu
          imagePullPolicy: Always
          name: ubuntu
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-12-05T07:13:11Z"
      lastUpdateTime: "2022-12-05T07:13:11Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-12-05T07:13:00Z"
      lastUpdateTime: "2022-12-05T07:13:11Z"
      message: ReplicaSet "ubuntu-deployment-696fdf7b4" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: DeploymentList
metadata:
  resourceVersion: "9742"
