---
apiVersion: v1
items:
- metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"k8s-workload-registrar","namespace":"spire"},"spec":{"ports":[{"name":"webhook","port":443,"protocol":"TCP","targetPort":9443}],"selector":{"app":"spire-server"},"type":"ClusterIP"}}
    creationTimestamp: "2022-12-23T13:21:04Z"
    name: k8s-workload-registrar
    namespace: spire
    resourceVersion: "628"
    uid: 5e5308ff-ac0b-47e6-8e82-c6a61aa81662
  spec:
    clusterIP: 10.96.22.192
    clusterIPs:
    - 10.96.22.192
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: webhook
      port: 443
      protocol: TCP
      targetPort: 9443
    selector:
      app: spire-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"spire-server","namespace":"spire"},"spec":{"ports":[{"name":"spire-server","port":8081,"protocol":"TCP","targetPort":8081},{"name":"spire-federation","port":8443,"protocol":"TCP","targetPort":8443}],"selector":{"app":"spire-server"},"type":"LoadBalancer"}}
    creationTimestamp: "2022-12-23T13:21:04Z"
    name: spire-server
    namespace: spire
    resourceVersion: "637"
    uid: 26a79999-b91d-4e0b-bf43-8c6b463098fc
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.96.231.16
    clusterIPs:
    - 10.96.231.16
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: spire-server
      nodePort: 30205
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: spire-federation
      nodePort: 31334
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app: spire-server
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 172.18.201.1
kind: ServiceList
metadata:
  resourceVersion: "3083"
