---
apiVersion: v1
items:
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T07:28:20Z"
  involvedObject:
    apiVersion: v1
    kind: Pod
    name: ubuntu-deployment-7b8975b5d6-qrwf2
    namespace: vl3-test
    resourceVersion: "19111"
    uid: 6843def8-2835-4c9a-be0c-efd042729fa5
  lastTimestamp: "2022-12-21T07:28:20Z"
  message: Successfully assigned vl3-test/ubuntu-deployment-7b8975b5d6-qrwf2 to kind-1-control-plane
  metadata:
    creationTimestamp: "2022-12-21T07:28:20Z"
    name: ubuntu-deployment-7b8975b5d6-qrwf2.1732be58f268a2a2
    namespace: vl3-test
    resourceVersion: "19116"
    uid: f4a0d630-f930-46a3-b810-cb597d64b725
  reason: Scheduled
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: default-scheduler
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T07:28:21Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.initContainers{istio-init}
    kind: Pod
    name: ubuntu-deployment-7b8975b5d6-qrwf2
    namespace: vl3-test
    resourceVersion: "19113"
    uid: 6843def8-2835-4c9a-be0c-efd042729fa5
  lastTimestamp: "2022-12-21T07:28:21Z"
  message: Container image "docker.io/istio/proxyv2:1.16.0" already present on machine
  metadata:
    creationTimestamp: "2022-12-21T07:28:21Z"
    name: ubuntu-deployment-7b8975b5d6-qrwf2.1732be590dbfd5ea
    namespace: vl3-test
    resourceVersion: "19124"
    uid: 430d2b84-2058-4e07-8d0d-5e554e7b5b4c
  reason: Pulled
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T07:28:21Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.initContainers{istio-init}
    kind: Pod
    name: ubuntu-deployment-7b8975b5d6-qrwf2
    namespace: vl3-test
    resourceVersion: "19113"
    uid: 6843def8-2835-4c9a-be0c-efd042729fa5
  lastTimestamp: "2022-12-21T07:28:21Z"
  message: Created container istio-init
  metadata:
    creationTimestamp: "2022-12-21T07:28:21Z"
    name: ubuntu-deployment-7b8975b5d6-qrwf2.1732be590fae3acd
    namespace: vl3-test
    resourceVersion: "19125"
    uid: 49636419-5a5d-480d-a55e-ff952cf5e14e
  reason: Created
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T07:28:21Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.initContainers{istio-init}
    kind: Pod
    name: ubuntu-deployment-7b8975b5d6-qrwf2
    namespace: vl3-test
    resourceVersion: "19113"
    uid: 6843def8-2835-4c9a-be0c-efd042729fa5
  lastTimestamp: "2022-12-21T07:28:21Z"
  message: Started container istio-init
  metadata:
    creationTimestamp: "2022-12-21T07:28:21Z"
    name: ubuntu-deployment-7b8975b5d6-qrwf2.1732be591b888385
    namespace: vl3-test
    resourceVersion: "19126"
    uid: ea1435a8-eb5f-42df-9e9c-1376ced30cc2
  reason: Started
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T07:28:22Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.initContainers{cmd-nsc-init}
    kind: Pod
    name: ubuntu-deployment-7b8975b5d6-qrwf2
    namespace: vl3-test
    resourceVersion: "19113"
    uid: 6843def8-2835-4c9a-be0c-efd042729fa5
  lastTimestamp: "2022-12-21T07:28:22Z"
  message: Container image "ghcr.io/networkservicemesh/cmd-nsc-init:v1.7.0-rc.2" already
    present on machine
  metadata:
    creationTimestamp: "2022-12-21T07:28:22Z"
    name: ubuntu-deployment-7b8975b5d6-qrwf2.1732be5955a83c95
    namespace: vl3-test
    resourceVersion: "19128"
    uid: ee140f22-6074-4297-9b0e-8da69fac6b7b
  reason: Pulled
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T07:28:22Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.initContainers{cmd-nsc-init}
    kind: Pod
    name: ubuntu-deployment-7b8975b5d6-qrwf2
    namespace: vl3-test
    resourceVersion: "19113"
    uid: 6843def8-2835-4c9a-be0c-efd042729fa5
  lastTimestamp: "2022-12-21T07:28:22Z"
  message: Created container cmd-nsc-init
  metadata:
    creationTimestamp: "2022-12-21T07:28:22Z"
    name: ubuntu-deployment-7b8975b5d6-qrwf2.1732be59570046ec
    namespace: vl3-test
    resourceVersion: "19130"
    uid: e22518f4-468a-40ac-bffa-d3cfff781769
  reason: Created
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T07:28:22Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.initContainers{cmd-nsc-init}
    kind: Pod
    name: ubuntu-deployment-7b8975b5d6-qrwf2
    namespace: vl3-test
    resourceVersion: "19113"
    uid: 6843def8-2835-4c9a-be0c-efd042729fa5
  lastTimestamp: "2022-12-21T07:28:22Z"
  message: Started container cmd-nsc-init
  metadata:
    creationTimestamp: "2022-12-21T07:28:22Z"
    name: ubuntu-deployment-7b8975b5d6-qrwf2.1732be595e53b815
    namespace: vl3-test
    resourceVersion: "19131"
    uid: eefb82d5-6659-4f6b-886e-cca1617bb38e
  reason: Started
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T07:28:24Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{ubuntu}
    kind: Pod
    name: ubuntu-deployment-7b8975b5d6-qrwf2
    namespace: vl3-test
    resourceVersion: "19113"
    uid: 6843def8-2835-4c9a-be0c-efd042729fa5
  lastTimestamp: "2022-12-21T07:28:24Z"
  message: Pulling image "ubuntu"
  metadata:
    creationTimestamp: "2022-12-21T07:28:24Z"
    name: ubuntu-deployment-7b8975b5d6-qrwf2.1732be59cda10682
    namespace: vl3-test
    resourceVersion: "19135"
    uid: 0d50f0bd-2853-41ac-ac09-01a9257821bd
  reason: Pulling
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T07:28:26Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{ubuntu}
    kind: Pod
    name: ubuntu-deployment-7b8975b5d6-qrwf2
    namespace: vl3-test
    resourceVersion: "19113"
    uid: 6843def8-2835-4c9a-be0c-efd042729fa5
  lastTimestamp: "2022-12-21T07:28:26Z"
  message: Successfully pulled image "ubuntu" in 1.86415716s
  metadata:
    creationTimestamp: "2022-12-21T07:28:26Z"
    name: ubuntu-deployment-7b8975b5d6-qrwf2.1732be5a3cc3cf30
    namespace: vl3-test
    resourceVersion: "19142"
    uid: c2e6086a-0762-47d8-9506-488f103936b1
  reason: Pulled
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T07:28:26Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{ubuntu}
    kind: Pod
    name: ubuntu-deployment-7b8975b5d6-qrwf2
    namespace: vl3-test
    resourceVersion: "19113"
    uid: 6843def8-2835-4c9a-be0c-efd042729fa5
  lastTimestamp: "2022-12-21T07:28:26Z"
  message: Created container ubuntu
  metadata:
    creationTimestamp: "2022-12-21T07:28:26Z"
    name: ubuntu-deployment-7b8975b5d6-qrwf2.1732be5a3dd44f03
    namespace: vl3-test
    resourceVersion: "19143"
    uid: ebc693e4-2fd8-4dbe-9770-f47d694ec089
  reason: Created
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T07:28:26Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{ubuntu}
    kind: Pod
    name: ubuntu-deployment-7b8975b5d6-qrwf2
    namespace: vl3-test
    resourceVersion: "19113"
    uid: 6843def8-2835-4c9a-be0c-efd042729fa5
  lastTimestamp: "2022-12-21T07:28:26Z"
  message: Started container ubuntu
  metadata:
    creationTimestamp: "2022-12-21T07:28:26Z"
    name: ubuntu-deployment-7b8975b5d6-qrwf2.1732be5a45145753
    namespace: vl3-test
    resourceVersion: "19144"
    uid: b26babfa-292a-450c-afda-a662b6c7408a
  reason: Started
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T07:28:26Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{istio-proxy}
    kind: Pod
    name: ubuntu-deployment-7b8975b5d6-qrwf2
    namespace: vl3-test
    resourceVersion: "19113"
    uid: 6843def8-2835-4c9a-be0c-efd042729fa5
  lastTimestamp: "2022-12-21T07:28:26Z"
  message: Container image "docker.io/istio/proxyv2:1.16.0" already present on machine
  metadata:
    creationTimestamp: "2022-12-21T07:28:26Z"
    name: ubuntu-deployment-7b8975b5d6-qrwf2.1732be5a451e8186
    namespace: vl3-test
    resourceVersion: "19145"
    uid: 206191a8-010f-47a1-9425-fd985cc7c08b
  reason: Pulled
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T07:28:26Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{istio-proxy}
    kind: Pod
    name: ubuntu-deployment-7b8975b5d6-qrwf2
    namespace: vl3-test
    resourceVersion: "19113"
    uid: 6843def8-2835-4c9a-be0c-efd042729fa5
  lastTimestamp: "2022-12-21T07:28:26Z"
  message: Created container istio-proxy
  metadata:
    creationTimestamp: "2022-12-21T07:28:26Z"
    name: ubuntu-deployment-7b8975b5d6-qrwf2.1732be5a46fdf209
    namespace: vl3-test
    resourceVersion: "19146"
    uid: c3d771d4-d6ff-4f25-afa3-a2bc01b66043
  reason: Created
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T07:28:26Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{istio-proxy}
    kind: Pod
    name: ubuntu-deployment-7b8975b5d6-qrwf2
    namespace: vl3-test
    resourceVersion: "19113"
    uid: 6843def8-2835-4c9a-be0c-efd042729fa5
  lastTimestamp: "2022-12-21T07:28:26Z"
  message: Started container istio-proxy
  metadata:
    creationTimestamp: "2022-12-21T07:28:26Z"
    name: ubuntu-deployment-7b8975b5d6-qrwf2.1732be5a4e0956b3
    namespace: vl3-test
    resourceVersion: "19147"
    uid: 8ed62d8d-22bf-4af2-bf5f-9ce41566a071
  reason: Started
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T07:28:26Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{cmd-nsc}
    kind: Pod
    name: ubuntu-deployment-7b8975b5d6-qrwf2
    namespace: vl3-test
    resourceVersion: "19113"
    uid: 6843def8-2835-4c9a-be0c-efd042729fa5
  lastTimestamp: "2022-12-21T07:28:26Z"
  message: Container image "ghcr.io/networkservicemesh/cmd-nsc:v1.7.0-rc.2" already
    present on machine
  metadata:
    creationTimestamp: "2022-12-21T07:28:26Z"
    name: ubuntu-deployment-7b8975b5d6-qrwf2.1732be5a4e132431
    namespace: vl3-test
    resourceVersion: "19148"
    uid: 622788c8-19fb-41e3-8e11-780da9e8a859
  reason: Pulled
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T07:28:26Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{cmd-nsc}
    kind: Pod
    name: ubuntu-deployment-7b8975b5d6-qrwf2
    namespace: vl3-test
    resourceVersion: "19113"
    uid: 6843def8-2835-4c9a-be0c-efd042729fa5
  lastTimestamp: "2022-12-21T07:28:26Z"
  message: Created container cmd-nsc
  metadata:
    creationTimestamp: "2022-12-21T07:28:26Z"
    name: ubuntu-deployment-7b8975b5d6-qrwf2.1732be5a4fa4e38b
    namespace: vl3-test
    resourceVersion: "19149"
    uid: 02bc457b-5871-4034-bd1d-fec9591d37b7
  reason: Created
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T07:28:26Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{cmd-nsc}
    kind: Pod
    name: ubuntu-deployment-7b8975b5d6-qrwf2
    namespace: vl3-test
    resourceVersion: "19113"
    uid: 6843def8-2835-4c9a-be0c-efd042729fa5
  lastTimestamp: "2022-12-21T07:28:26Z"
  message: Started container cmd-nsc
  metadata:
    creationTimestamp: "2022-12-21T07:28:26Z"
    name: ubuntu-deployment-7b8975b5d6-qrwf2.1732be5a55e7c59f
    namespace: vl3-test
    resourceVersion: "19150"
    uid: ce9f864c-1d5a-4676-ac7a-1fc7e914a27a
  reason: Started
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 9
  eventTime: null
  firstTimestamp: "2022-12-21T07:28:27Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{istio-proxy}
    kind: Pod
    name: ubuntu-deployment-7b8975b5d6-qrwf2
    namespace: vl3-test
    resourceVersion: "19113"
    uid: 6843def8-2835-4c9a-be0c-efd042729fa5
  lastTimestamp: "2022-12-21T07:28:41Z"
  message: 'Readiness probe failed: Get "http://10.244.0.21:15021/healthz/ready":
    dial tcp 10.244.0.21:15021: connect: connection refused'
  metadata:
    creationTimestamp: "2022-12-21T07:28:27Z"
    name: ubuntu-deployment-7b8975b5d6-qrwf2.1732be5a818e4893
    namespace: vl3-test
    resourceVersion: "19186"
    uid: 10a90141-c95d-4648-b696-595bfd719424
  reason: Unhealthy
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Warning
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T07:28:20Z"
  involvedObject:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: ubuntu-deployment-7b8975b5d6
    namespace: vl3-test
    resourceVersion: "19108"
    uid: 188a653e-8a04-41ff-be60-ac7e9a7c9111
  lastTimestamp: "2022-12-21T07:28:20Z"
  message: 'Created pod: ubuntu-deployment-7b8975b5d6-qrwf2'
  metadata:
    creationTimestamp: "2022-12-21T07:28:20Z"
    name: ubuntu-deployment-7b8975b5d6.1732be58f1fa3bb4
    namespace: vl3-test
    resourceVersion: "19115"
    uid: 59ab1f9a-3a3b-44c8-b50c-d34d063f0f0d
  reason: SuccessfulCreate
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: replicaset-controller
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T07:28:20Z"
  involvedObject:
    apiVersion: apps/v1
    kind: Deployment
    name: ubuntu-deployment
    namespace: vl3-test
    resourceVersion: "19107"
    uid: 29620e41-bc1c-46c5-aafa-cc229c5e4e5e
  lastTimestamp: "2022-12-21T07:28:20Z"
  message: Scaled up replica set ubuntu-deployment-7b8975b5d6 to 1
  metadata:
    creationTimestamp: "2022-12-21T07:28:20Z"
    name: ubuntu-deployment.1732be58f061e40b
    namespace: vl3-test
    resourceVersion: "19109"
    uid: a444a2df-4e6e-4e7c-a050-c4eb6f5f6b8c
  reason: ScalingReplicaSet
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: deployment-controller
  type: Normal
kind: EventList
metadata:
  resourceVersion: "19318"
