---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=ef02275eec2ad9601b41fabf40de496dd6b8dac4
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=ef02275eec2ad9601b41fabf40de496dd6b8dac4

resources:
- namespace.yaml

patchesStrategicMerge:
- nse-patch.yaml
