---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-annotated-namespace

resources:
  - netsvc.yaml
  - namespace.yaml

bases:
  - https://github.com/networkservicemesh/deployments-k8s/apps/nse-kernel?ref=f2f32c367a72a5ebd5d43fe6a9d8aa13d38dd71c

patchesStrategicMerge:
  - patch-nse.yaml
