---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-annotated-namespace

resources:
  - netsvc.yaml
  - namespace.yaml

bases:
  - https://github.com/networkservicemesh/deployments-k8s/apps/nse-kernel?ref=9eeff3941ac2efd87d1e3775e7c4803474078192

patchesStrategicMerge:
  - patch-nse.yaml
