apiVersion: v1
data:
  root-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIC/TCCAeWgAwIBAgIRAP3nZ30hy4xp3clSUYygZ8UwDQYJKoZIhvcNAQELBQAw
    GDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDAeFw0yMzAxMDkwNTMxMTRaFw0zMzAx
    MDYwNTMxMTRaMBgxFjAUBgNVBAoTDWNsdXN0ZXIubG9jYWwwggEiMA0GCSqGSIb3
    DQEBAQUAA4IBDwAwggEKAoIBAQDUT9CZ+kwVixrhcWfg6tgdG6/zOalDsCMDSeF+
    wMz4/MjRZLZEOxcaiwp5tPVxRISQ89TfygD1rX1FtwOHS0D4tqUp52pZhoyhPiK6
    Ij0Pq4+l6ixYYKkF6Pn+44oxrg03HfoCkIXTgaLGa0fcc3QkmuE+Eulj7tGs13XJ
    lUdabSoPe35Tm/ZbpqvPA3LGgyTc6qigIN7tXXJ1LH50ksa3B1K4DN56WSUqO7oN
    YWCDXFRwmZhXSy4C6MQAftzjuB9+IlvwtQQB/fT5biuOdDhgsiHNMkz0K24cYQaa
    rwyBtC6Ehkx64LyTO0OSfqviw3AQpwM+ui4WFt0VG6ARBm3lAgMBAAGjQjBAMA4G
    A1UdDwEB/wQEAwICBDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRrV5NTIqoj
    Ao3PFbR88K12zqtpYzANBgkqhkiG9w0BAQsFAAOCAQEAOi9FRD0Scdp3gjicITOS
    T9tSs94v6JPJ/n4OVqMtbj0UIujvnEtztxtb/QAYdYqGvSXzfbTJDwdLGzcJOvFz
    urFEyMNvM+n5748Nr5WHFJ41Aw7+cc7EsQI4ics1ReQUl3c0yU4+1FD6j3v4DUKQ
    t6VrU58EwKHx/dngWKWSw5sywyHvnFZNGsmFmKHukyP8ujx94xDebb+Q3qa0k7xJ
    aRUBvQnJhZ9Z5C1avT6EUSc6Zo2AckTjqvzZJko6Z90HGd2XTqD2SJQr/BjmaupD
    d0JaOPX8qcaPlaeP31KWYxmk18R6j4MvByopJ9an9ATAKCSOC4FGOTKHdj6Fqg5/
    kg==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: "2023-01-09T05:31:15Z"
  labels:
    istio.io/config: "true"
  name: istio-ca-root-cert
  namespace: default
  resourceVersion: "1475"
  uid: 16012aa4-7d07-422f-9bbe-ec7a9c7d206e
