---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=9f92298f36dfb49dccf5736ef899cc149235b00b
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=9f92298f36dfb49dccf5736ef899cc149235b00b

resources:
- namespace.yaml

patchesStrategicMerge:
- nse-patch.yaml
