---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=v1.7.0-rc.2
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=v1.7.0-rc.2

resources:
- namespace.yaml

patchesStrategicMerge:
- nse-patch.yaml
