---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=88fa4d08aca35783d6aab60f1bf0233d2d01130a
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=88fa4d08aca35783d6aab60f1bf0233d2d01130a

resources:
- namespace.yaml

patchesStrategicMerge:
- nse-patch.yaml
