---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=689869e015c4b2c6b0f41944c25df712d5ee2fd7
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=689869e015c4b2c6b0f41944c25df712d5ee2fd7

resources:
- namespace.yaml

patchesStrategicMerge:
- nse-patch.yaml
