---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=9eeff3941ac2efd87d1e3775e7c4803474078192
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=9eeff3941ac2efd87d1e3775e7c4803474078192

resources:
- namespace.yaml

patchesStrategicMerge:
- nse-patch.yaml
