---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=f2f32c367a72a5ebd5d43fe6a9d8aa13d38dd71c
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=f2f32c367a72a5ebd5d43fe6a9d8aa13d38dd71c

resources:
- namespace.yaml

patchesStrategicMerge:
- nse-patch.yaml
