---
apiVersion: apps/v1
items:
- metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2022-12-21T05:12:33Z"
    generation: 1
    labels:
      app: nse-vl3-vpp
      pod-template-hash: 5d97745888
      spiffe.io/spiffe-id: "true"
    name: nse-vl3-vpp-5d97745888
    namespace: ns-dns-vl3
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: nse-vl3-vpp
      uid: e8d771ab-767c-4181-b577-faefcb2a65b1
    resourceVersion: "16963"
    uid: 4db40e8e-f48e-4e09-9930-72d30426d0e0
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: nse-vl3-vpp
        pod-template-hash: 5d97745888
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: nse-vl3-vpp
          pod-template-hash: 5d97745888
          spiffe.io/spiffe-id: "true"
      spec:
        containers:
        - env:
          - name: NSM_SERVICE_NAMES
            value: my-vl3-network
          - name: NSM_REGISTER_SERVICE
            value: "true"
          - name: NSM_DNS_TEMPLATES
            value: '{{ index .Labels "dnsName" }}.{{ .NetworkService }}.'
          - name: SPIFFE_ENDPOINT_SOCKET
            value: unix:///run/spire/sockets/agent.sock
          - name: NSM_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: NSM_LOG_LEVEL
            value: TRACE
          image: ghcr.io/networkservicemesh/cmd-nse-vl3-vpp:v1.7.0-rc.2
          imagePullPolicy: IfNotPresent
          name: nse
          resources:
            limits:
              cpu: 500m
              memory: 400Mi
            requests:
              cpu: 150m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /run/spire/sockets
            name: spire-agent-socket
            readOnly: true
          - mountPath: /var/lib/networkservicemesh
            name: nsm-socket
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /run/spire/sockets
            type: Directory
          name: spire-agent-socket
        - hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
          name: nsm-socket
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
- metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2022-12-21T05:12:33Z"
    generation: 1
    labels:
      app: vl3-ipam
      pod-template-hash: 7d564f85b
      spiffe.io/spiffe-id: "true"
    name: vl3-ipam-7d564f85b
    namespace: ns-dns-vl3
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: vl3-ipam
      uid: ea108f9a-9b99-4824-9425-b8fce162efe3
    resourceVersion: "3971"
    uid: 5e8e856e-1074-41ba-a6e5-2d6e44239466
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: vl3-ipam
        pod-template-hash: 7d564f85b
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: vl3-ipam
          pod-template-hash: 7d564f85b
          spiffe.io/spiffe-id: "true"
      spec:
        containers:
        - env:
          - name: SPIFFE_ENDPOINT_SOCKET
            value: unix:///run/spire/sockets/agent.sock
          - name: NSM_LISTEN_ON
            value: tcp://:5006
          - name: NSM_PREFIX
            value: 172.16.0.0/16
          - name: NSM_LOG_LEVEL
            value: TRACE
          image: ghcr.io/networkservicemesh/cmd-ipam-vl3:v1.7.0-rc.2
          imagePullPolicy: IfNotPresent
          name: vl3-ipam
          ports:
          - containerPort: 5006
            hostPort: 5006
            protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 40Mi
            requests:
              cpu: 100m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /run/spire/sockets
            name: spire-agent-socket
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /run/spire/sockets
            type: Directory
          name: spire-agent-socket
        - hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
          name: nsm-socket
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
kind: ReplicaSetList
metadata:
  resourceVersion: "19315"
