---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-webhook-k8s
  labels:
    app: proxy-webhook-k8s
spec:
  selector:
    matchLabels:
      app: proxy-webhook-k8s
  template:
    metadata:
      labels:
        app: proxy-webhook-k8s
    spec:
      serviceAccount: proxy-webhook-sa
      containers:
        - name: proxy-webhook-k8s
          image: proxy-webhook:5
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /ready
              port: 443
              scheme: HTTPS
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_SERVICE_NAME
              value: proxy-webhook-svc
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NSM_ANNOTATION
              value: networkservicemesh.io
            - name: NSM_CONTAINER_IMAGES
              value: ghcr.io/networkservicemesh/cmd-nsc:v1.7.0-rc.2
            - name: NSM_INIT_CONTAINER_IMAGES
              value: ghcr.io/networkservicemesh/cmd-nsc-init:v1.7.0-rc.2
            - name: NSM_LABELS
              value: spiffe.io/spiffe-id:true
            - name: NSM_ENVS
              value: NSM_LOG_LEVEL=TRACE
              # value: NSM_LOG_LEVEL=TRACE,NSM_LIVENESSCHECKENABLED=False
