apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"admissionregistration.k8s.io/v1","kind":"MutatingWebhookConfiguration","metadata":{"annotations":{},"labels":{"app":"sidecar-injector","install.operator.istio.io/owning-resource":"unknown","install.operator.istio.io/owning-resource-namespace":"istio-system","istio.io/rev":"default","operator.istio.io/component":"Pilot","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.16.0","release":"istio"},"name":"istio-sidecar-injector"},"webhooks":[{"admissionReviewVersions":["v1beta1","v1"],"clientConfig":{"service":{"name":"istiod","namespace":"istio-system","path":"/inject","port":443}},"failurePolicy":"Fail","name":"rev.namespace.sidecar-injector.istio.io","namespaceSelector":{"matchExpressions":[{"key":"istio.io/rev","operator":"In","values":["default"]},{"key":"istio-injection","operator":"DoesNotExist"}]},"objectSelector":{"matchExpressions":[{"key":"sidecar.istio.io/inject","operator":"NotIn","values":["false"]}]},"rules":[{"apiGroups":[""],"apiVersions":["v1"],"operations":["CREATE"],"resources":["pods"]}],"sideEffects":"None"},{"admissionReviewVersions":["v1beta1","v1"],"clientConfig":{"service":{"name":"istiod","namespace":"istio-system","path":"/inject","port":443}},"failurePolicy":"Fail","name":"rev.object.sidecar-injector.istio.io","namespaceSelector":{"matchExpressions":[{"key":"istio.io/rev","operator":"DoesNotExist"},{"key":"istio-injection","operator":"DoesNotExist"}]},"objectSelector":{"matchExpressions":[{"key":"sidecar.istio.io/inject","operator":"NotIn","values":["false"]},{"key":"istio.io/rev","operator":"In","values":["default"]}]},"rules":[{"apiGroups":[""],"apiVersions":["v1"],"operations":["CREATE"],"resources":["pods"]}],"sideEffects":"None"},{"admissionReviewVersions":["v1beta1","v1"],"clientConfig":{"service":{"name":"istiod","namespace":"istio-system","path":"/inject","port":443}},"failurePolicy":"Fail","name":"namespace.sidecar-injector.istio.io","namespaceSelector":{"matchExpressions":[{"key":"istio-injection","operator":"In","values":["enabled"]}]},"objectSelector":{"matchExpressions":[{"key":"sidecar.istio.io/inject","operator":"NotIn","values":["false"]}]},"rules":[{"apiGroups":[""],"apiVersions":["v1"],"operations":["CREATE"],"resources":["pods"]}],"sideEffects":"None"},{"admissionReviewVersions":["v1beta1","v1"],"clientConfig":{"service":{"name":"istiod","namespace":"istio-system","path":"/inject","port":443}},"failurePolicy":"Fail","name":"object.sidecar-injector.istio.io","namespaceSelector":{"matchExpressions":[{"key":"istio-injection","operator":"DoesNotExist"},{"key":"istio.io/rev","operator":"DoesNotExist"}]},"objectSelector":{"matchExpressions":[{"key":"sidecar.istio.io/inject","operator":"In","values":["true"]},{"key":"istio.io/rev","operator":"DoesNotExist"}]},"rules":[{"apiGroups":[""],"apiVersions":["v1"],"operations":["CREATE"],"resources":["pods"]}],"sideEffects":"None"}]}
  creationTimestamp: "2023-01-17T05:10:14Z"
  generation: 3
  labels:
    app: sidecar-injector
    install.operator.istio.io/owning-resource: unknown
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: default
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.16.0
    release: istio
  name: istio-sidecar-injector
  resourceVersion: "32298"
  uid: 22ec64cf-9b80-48ab-a200-5f45aff4e40c
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvRENDQWVTZ0F3SUJBZ0lRZVZTaXdVbUVHZXlMMEIvZlN0bGg4akFOQmdrcWhraUc5dzBCQVFzRkFEQVkKTVJZd0ZBWURWUVFLRXcxamJIVnpkR1Z5TG14dlkyRnNNQjRYRFRJek1ERXhOekExTVRBeU5Wb1hEVE16TURFeApOREExTVRBeU5Wb3dHREVXTUJRR0ExVUVDaE1OWTJ4MWMzUmxjaTVzYjJOaGJEQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFQbE8xMmJJejkxVTFHZEp5K1dXejY3dGRETGVlZDUzYlhXN0padkIKTk1kMWdLZVNoSmFWaXl3a0tVb1hNUzFYTFhzQnFtcTNyUnN1ci85NzA5UmxYV0ZEMnhUd2ZEMS9lcXVQOFFsMwpudzVpVmlNd0d1Q2MzeTd4OEkrWE9WeUpoZ3RQWHdXTk5Dbm5ZaVNwR3lrMjZGdGpxZDVjMlo0dmR6RVkwRlovClZ2UXZBb1JqNW5wQ1dhS1BSQjg5N2pLa2FkU0NEQnpoTVB5K21SejVSUnlqYXpCdTBzMUVuQ0UvTDFQL3hPc0QKdkNUN1gzY25uU1BHMitEbzlZbC80MkpPcSs1TlNVRkV1d0txTklNTnZLWUlkem1OS0tsM1kzVytPckJsM012SgpuY2VGazM5dnJHWU5SN3d5djFYZGxRQUpCb0R4UStudStZTmNGV0Juc2J4ejdnVUNBd0VBQWFOQ01FQXdEZ1lEClZSMFBBUUgvQkFRREFnSUVNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGSkZvNnJTVUM3bEoKVCtYeENFWnQ0clQyK0NQYk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ1hyM3JxR0d0UzRrUTRzU1ZUSU91VwpaS3VHak0yTGtudmtwNzRFcFNScGVJU0hzUWI4K3psT05zTVNHRlFwK3YrRmVWZlRMb01QZXFNUDhCTjBCdDVWCjQyVGVkZVBpcTR0aHRsamh2WDl2dXA3UWp5Uk5KOUw3cFcvL3Z6RVBZRlE2VWwwY2p1aHhjQ2lKcXA5NUM0WlQKMzZuak8ydWgvclpES1A5aHUxU1JMT1pGSzJaUFJRUEVtN0h4UmlBZlExb01jK0xZaFlxZHVTTFB0VDNFbW9KcApEQmp1WlY2RmJwVGdEN1BlZmZpTGdQN3BHWEYyb1NJWkNScFRJc3dubzFqbE1Pa0VMeStkRGU1L2pwL2ZlWHFyCkpScU1FaTkyK0g3cUhMQjMxS290VDV1TWE4SDVES3ZmK2pQQnpPdmNRcE9LaUVYWnJJQUV6MTROT1lwSXA0TnYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: istiod
      namespace: istio-system
      path: /inject
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: rev.namespace.sidecar-injector.istio.io
  namespaceSelector:
    matchLabels:
      istio.io/deactivated: never-match
  objectSelector:
    matchLabels:
      istio.io/deactivated: never-match
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvRENDQWVTZ0F3SUJBZ0lRZVZTaXdVbUVHZXlMMEIvZlN0bGg4akFOQmdrcWhraUc5dzBCQVFzRkFEQVkKTVJZd0ZBWURWUVFLRXcxamJIVnpkR1Z5TG14dlkyRnNNQjRYRFRJek1ERXhOekExTVRBeU5Wb1hEVE16TURFeApOREExTVRBeU5Wb3dHREVXTUJRR0ExVUVDaE1OWTJ4MWMzUmxjaTVzYjJOaGJEQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFQbE8xMmJJejkxVTFHZEp5K1dXejY3dGRETGVlZDUzYlhXN0padkIKTk1kMWdLZVNoSmFWaXl3a0tVb1hNUzFYTFhzQnFtcTNyUnN1ci85NzA5UmxYV0ZEMnhUd2ZEMS9lcXVQOFFsMwpudzVpVmlNd0d1Q2MzeTd4OEkrWE9WeUpoZ3RQWHdXTk5Dbm5ZaVNwR3lrMjZGdGpxZDVjMlo0dmR6RVkwRlovClZ2UXZBb1JqNW5wQ1dhS1BSQjg5N2pLa2FkU0NEQnpoTVB5K21SejVSUnlqYXpCdTBzMUVuQ0UvTDFQL3hPc0QKdkNUN1gzY25uU1BHMitEbzlZbC80MkpPcSs1TlNVRkV1d0txTklNTnZLWUlkem1OS0tsM1kzVytPckJsM012SgpuY2VGazM5dnJHWU5SN3d5djFYZGxRQUpCb0R4UStudStZTmNGV0Juc2J4ejdnVUNBd0VBQWFOQ01FQXdEZ1lEClZSMFBBUUgvQkFRREFnSUVNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGSkZvNnJTVUM3bEoKVCtYeENFWnQ0clQyK0NQYk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ1hyM3JxR0d0UzRrUTRzU1ZUSU91VwpaS3VHak0yTGtudmtwNzRFcFNScGVJU0hzUWI4K3psT05zTVNHRlFwK3YrRmVWZlRMb01QZXFNUDhCTjBCdDVWCjQyVGVkZVBpcTR0aHRsamh2WDl2dXA3UWp5Uk5KOUw3cFcvL3Z6RVBZRlE2VWwwY2p1aHhjQ2lKcXA5NUM0WlQKMzZuak8ydWgvclpES1A5aHUxU1JMT1pGSzJaUFJRUEVtN0h4UmlBZlExb01jK0xZaFlxZHVTTFB0VDNFbW9KcApEQmp1WlY2RmJwVGdEN1BlZmZpTGdQN3BHWEYyb1NJWkNScFRJc3dubzFqbE1Pa0VMeStkRGU1L2pwL2ZlWHFyCkpScU1FaTkyK0g3cUhMQjMxS290VDV1TWE4SDVES3ZmK2pQQnpPdmNRcE9LaUVYWnJJQUV6MTROT1lwSXA0TnYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: istiod
      namespace: istio-system
      path: /inject
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: rev.object.sidecar-injector.istio.io
  namespaceSelector:
    matchLabels:
      istio.io/deactivated: never-match
  objectSelector:
    matchLabels:
      istio.io/deactivated: never-match
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvRENDQWVTZ0F3SUJBZ0lRZVZTaXdVbUVHZXlMMEIvZlN0bGg4akFOQmdrcWhraUc5dzBCQVFzRkFEQVkKTVJZd0ZBWURWUVFLRXcxamJIVnpkR1Z5TG14dlkyRnNNQjRYRFRJek1ERXhOekExTVRBeU5Wb1hEVE16TURFeApOREExTVRBeU5Wb3dHREVXTUJRR0ExVUVDaE1OWTJ4MWMzUmxjaTVzYjJOaGJEQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFQbE8xMmJJejkxVTFHZEp5K1dXejY3dGRETGVlZDUzYlhXN0padkIKTk1kMWdLZVNoSmFWaXl3a0tVb1hNUzFYTFhzQnFtcTNyUnN1ci85NzA5UmxYV0ZEMnhUd2ZEMS9lcXVQOFFsMwpudzVpVmlNd0d1Q2MzeTd4OEkrWE9WeUpoZ3RQWHdXTk5Dbm5ZaVNwR3lrMjZGdGpxZDVjMlo0dmR6RVkwRlovClZ2UXZBb1JqNW5wQ1dhS1BSQjg5N2pLa2FkU0NEQnpoTVB5K21SejVSUnlqYXpCdTBzMUVuQ0UvTDFQL3hPc0QKdkNUN1gzY25uU1BHMitEbzlZbC80MkpPcSs1TlNVRkV1d0txTklNTnZLWUlkem1OS0tsM1kzVytPckJsM012SgpuY2VGazM5dnJHWU5SN3d5djFYZGxRQUpCb0R4UStudStZTmNGV0Juc2J4ejdnVUNBd0VBQWFOQ01FQXdEZ1lEClZSMFBBUUgvQkFRREFnSUVNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGSkZvNnJTVUM3bEoKVCtYeENFWnQ0clQyK0NQYk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ1hyM3JxR0d0UzRrUTRzU1ZUSU91VwpaS3VHak0yTGtudmtwNzRFcFNScGVJU0hzUWI4K3psT05zTVNHRlFwK3YrRmVWZlRMb01QZXFNUDhCTjBCdDVWCjQyVGVkZVBpcTR0aHRsamh2WDl2dXA3UWp5Uk5KOUw3cFcvL3Z6RVBZRlE2VWwwY2p1aHhjQ2lKcXA5NUM0WlQKMzZuak8ydWgvclpES1A5aHUxU1JMT1pGSzJaUFJRUEVtN0h4UmlBZlExb01jK0xZaFlxZHVTTFB0VDNFbW9KcApEQmp1WlY2RmJwVGdEN1BlZmZpTGdQN3BHWEYyb1NJWkNScFRJc3dubzFqbE1Pa0VMeStkRGU1L2pwL2ZlWHFyCkpScU1FaTkyK0g3cUhMQjMxS290VDV1TWE4SDVES3ZmK2pQQnpPdmNRcE9LaUVYWnJJQUV6MTROT1lwSXA0TnYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: istiod
      namespace: istio-system
      path: /inject
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: namespace.sidecar-injector.istio.io
  namespaceSelector:
    matchLabels:
      istio.io/deactivated: never-match
  objectSelector:
    matchLabels:
      istio.io/deactivated: never-match
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvRENDQWVTZ0F3SUJBZ0lRZVZTaXdVbUVHZXlMMEIvZlN0bGg4akFOQmdrcWhraUc5dzBCQVFzRkFEQVkKTVJZd0ZBWURWUVFLRXcxamJIVnpkR1Z5TG14dlkyRnNNQjRYRFRJek1ERXhOekExTVRBeU5Wb1hEVE16TURFeApOREExTVRBeU5Wb3dHREVXTUJRR0ExVUVDaE1OWTJ4MWMzUmxjaTVzYjJOaGJEQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFQbE8xMmJJejkxVTFHZEp5K1dXejY3dGRETGVlZDUzYlhXN0padkIKTk1kMWdLZVNoSmFWaXl3a0tVb1hNUzFYTFhzQnFtcTNyUnN1ci85NzA5UmxYV0ZEMnhUd2ZEMS9lcXVQOFFsMwpudzVpVmlNd0d1Q2MzeTd4OEkrWE9WeUpoZ3RQWHdXTk5Dbm5ZaVNwR3lrMjZGdGpxZDVjMlo0dmR6RVkwRlovClZ2UXZBb1JqNW5wQ1dhS1BSQjg5N2pLa2FkU0NEQnpoTVB5K21SejVSUnlqYXpCdTBzMUVuQ0UvTDFQL3hPc0QKdkNUN1gzY25uU1BHMitEbzlZbC80MkpPcSs1TlNVRkV1d0txTklNTnZLWUlkem1OS0tsM1kzVytPckJsM012SgpuY2VGazM5dnJHWU5SN3d5djFYZGxRQUpCb0R4UStudStZTmNGV0Juc2J4ejdnVUNBd0VBQWFOQ01FQXdEZ1lEClZSMFBBUUgvQkFRREFnSUVNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGSkZvNnJTVUM3bEoKVCtYeENFWnQ0clQyK0NQYk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ1hyM3JxR0d0UzRrUTRzU1ZUSU91VwpaS3VHak0yTGtudmtwNzRFcFNScGVJU0hzUWI4K3psT05zTVNHRlFwK3YrRmVWZlRMb01QZXFNUDhCTjBCdDVWCjQyVGVkZVBpcTR0aHRsamh2WDl2dXA3UWp5Uk5KOUw3cFcvL3Z6RVBZRlE2VWwwY2p1aHhjQ2lKcXA5NUM0WlQKMzZuak8ydWgvclpES1A5aHUxU1JMT1pGSzJaUFJRUEVtN0h4UmlBZlExb01jK0xZaFlxZHVTTFB0VDNFbW9KcApEQmp1WlY2RmJwVGdEN1BlZmZpTGdQN3BHWEYyb1NJWkNScFRJc3dubzFqbE1Pa0VMeStkRGU1L2pwL2ZlWHFyCkpScU1FaTkyK0g3cUhMQjMxS290VDV1TWE4SDVES3ZmK2pQQnpPdmNRcE9LaUVYWnJJQUV6MTROT1lwSXA0TnYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: istiod
      namespace: istio-system
      path: /inject
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: object.sidecar-injector.istio.io
  namespaceSelector:
    matchLabels:
      istio.io/deactivated: never-match
  objectSelector:
    matchLabels:
      istio.io/deactivated: never-match
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
