---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-firewall-vpp?ref=8a7a76dbe9267313397e7e59d6c9fb457de3a285
patchesStrategicMerge:
- patch-nse-firewall-vpp.yaml
- config-patch.yaml
