---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spire

resources:
- k8s-workload-registrar-crd.yaml
- spire-namespace.yaml
- agent-account.yaml
- agent-cluster-role.yaml
- agent-daemonset.yaml
- server-account.yaml
- server-cluster-role.yaml
- server-service.yaml
- server-statefulset.yaml
- spire-bundle-configmap.yaml
- k8s-workload-registrar-cluster-role.yaml
- k8s-workload-registrar-service.yaml
- k8s-workload-registrar-validating-webhook-configuration.yaml
