apiVersion: v1
kind: Service
metadata:
  name: spire-server-nodeport
  namespace: spire
spec:
  type: NodePort
  ports:
  - name: spire-server
    nodePort: 30000
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: spire-server
