---
apiVersion: apps/v1
items:
- metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2022-12-05T07:58:02Z"
    generation: 1
    labels:
      app: ubuntu
      pod-template-hash: 696fdf7b4
    name: ubuntu-deployment-696fdf7b4
    namespace: ubuntu-ns
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: ubuntu-deployment
      uid: 7471371d-69f5-44ad-ac05-ee9519d251bf
    resourceVersion: "9160"
    uid: bf23484b-c475-4062-a47b-4e8125fbd1ac
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ubuntu
        pod-template-hash: 696fdf7b4
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ubuntu
          pod-template-hash: 696fdf7b4
      spec:
        containers:
        - command:
          - sleep
          - "123456"
          image: ubuntu
          imagePullPolicy: Always
          name: ubuntu
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
kind: ReplicaSetList
metadata:
  resourceVersion: "15807"
