---
apiVersion: apps/v1
items:
- metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"helloworld","version":"v1"},"name":"helloworld-v1","namespace":"sample"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"helloworld","version":"v1"}},"template":{"metadata":{"labels":{"app":"helloworld","version":"v1"}},"spec":{"containers":[{"image":"docker.io/istio/examples-helloworld-v1","imagePullPolicy":"IfNotPresent","name":"helloworld","ports":[{"containerPort":5000}],"resources":{"requests":{"cpu":"100m"}}}]}}}}
    creationTimestamp: "2022-12-05T07:16:44Z"
    generation: 1
    labels:
      app: helloworld
      version: v1
    name: helloworld-v1
    namespace: sample
    resourceVersion: "4014"
    uid: 0d3c561b-47d2-4371-bfc2-156e28b6db56
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: helloworld
        version: v1
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: helloworld
          version: v1
      spec:
        containers:
        - image: docker.io/istio/examples-helloworld-v1
          imagePullPolicy: IfNotPresent
          name: helloworld
          ports:
          - containerPort: 5000
            protocol: TCP
          resources:
            requests:
              cpu: 100m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-12-05T07:17:36Z"
      lastUpdateTime: "2022-12-05T07:17:36Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-12-05T07:16:44Z"
      lastUpdateTime: "2022-12-05T07:17:36Z"
      message: ReplicaSet "helloworld-v1-78b9f5c87f" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: DeploymentList
metadata:
  resourceVersion: "15800"
