---
apiVersion: v1
items:
- metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"helloworld","service":"helloworld"},"name":"helloworld","namespace":"sample"},"spec":{"ports":[{"name":"http","port":5000}],"selector":{"app":"helloworld"}}}
    creationTimestamp: "2022-12-05T07:16:44Z"
    labels:
      app: helloworld
      service: helloworld
    name: helloworld
    namespace: sample
    resourceVersion: "3844"
    uid: a263f314-bc5f-499e-aa7d-770a084e74aa
  spec:
    clusterIP: 10.96.137.147
    clusterIPs:
    - 10.96.137.147
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      app: helloworld
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: ServiceList
metadata:
  resourceVersion: "15800"
