---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-nse-composition

resources:
- ns-nse-composition.yaml
- config-file.yaml
- nse-composition-ns.yaml

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-kernel?ref=8a7a76dbe9267313397e7e59d6c9fb457de3a285
- nse-firewall

patchesStrategicMerge:
- patch-nse.yaml

configMapGenerator:
  - name: nginx-config
    files:
      - nginx.conf
