---
apiVersion: apps/v1
items:
- metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"nse-vl3-vpp"},"name":"nse-vl3-vpp","namespace":"ns-dns-vl3"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nse-vl3-vpp"}},"template":{"metadata":{"labels":{"app":"nse-vl3-vpp","spiffe.io/spiffe-id":"true"}},"spec":{"containers":[{"env":[{"name":"NSM_SERVICE_NAMES","value":"my-vl3-network"},{"name":"NSM_REGISTER_SERVICE","value":"true"},{"name":"NSM_DNS_TEMPLATES","value":"{{ index .Labels \"dnsName\" }}.{{ .NetworkService }}."},{"name":"SPIFFE_ENDPOINT_SOCKET","value":"unix:///run/spire/sockets/agent.sock"},{"name":"NSM_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"NSM_LOG_LEVEL","value":"TRACE"}],"image":"ghcr.io/networkservicemesh/cmd-nse-vl3-vpp:v1.7.0-rc.2","imagePullPolicy":"IfNotPresent","name":"nse","resources":{"limits":{"cpu":"500m","memory":"400Mi"},"requests":{"cpu":"150m"}},"volumeMounts":[{"mountPath":"/run/spire/sockets","name":"spire-agent-socket","readOnly":true},{"mountPath":"/var/lib/networkservicemesh","name":"nsm-socket","readOnly":true}]}],"volumes":[{"hostPath":{"path":"/run/spire/sockets","type":"Directory"},"name":"spire-agent-socket"},{"hostPath":{"path":"/var/lib/networkservicemesh","type":"DirectoryOrCreate"},"name":"nsm-socket"}]}}}}
    creationTimestamp: "2022-12-21T05:12:33Z"
    generation: 1
    labels:
      app: nse-vl3-vpp
    name: nse-vl3-vpp
    namespace: ns-dns-vl3
    resourceVersion: "16964"
    uid: e8d771ab-767c-4181-b577-faefcb2a65b1
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: nse-vl3-vpp
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: nse-vl3-vpp
          spiffe.io/spiffe-id: "true"
      spec:
        containers:
        - env:
          - name: NSM_SERVICE_NAMES
            value: my-vl3-network
          - name: NSM_REGISTER_SERVICE
            value: "true"
          - name: NSM_DNS_TEMPLATES
            value: '{{ index .Labels "dnsName" }}.{{ .NetworkService }}.'
          - name: SPIFFE_ENDPOINT_SOCKET
            value: unix:///run/spire/sockets/agent.sock
          - name: NSM_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: NSM_LOG_LEVEL
            value: TRACE
          image: ghcr.io/networkservicemesh/cmd-nse-vl3-vpp:v1.7.0-rc.2
          imagePullPolicy: IfNotPresent
          name: nse
          resources:
            limits:
              cpu: 500m
              memory: 400Mi
            requests:
              cpu: 150m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /run/spire/sockets
            name: spire-agent-socket
            readOnly: true
          - mountPath: /var/lib/networkservicemesh
            name: nsm-socket
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /run/spire/sockets
            type: Directory
          name: spire-agent-socket
        - hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
          name: nsm-socket
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-12-21T05:12:33Z"
      lastUpdateTime: "2022-12-21T05:12:55Z"
      message: ReplicaSet "nse-vl3-vpp-5d97745888" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2022-12-21T07:10:23Z"
      lastUpdateTime: "2022-12-21T07:10:23Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"vl3-ipam"},"name":"vl3-ipam","namespace":"ns-dns-vl3"},"spec":{"selector":{"matchLabels":{"app":"vl3-ipam"}},"template":{"metadata":{"labels":{"app":"vl3-ipam","spiffe.io/spiffe-id":"true"}},"spec":{"containers":[{"env":[{"name":"SPIFFE_ENDPOINT_SOCKET","value":"unix:///run/spire/sockets/agent.sock"},{"name":"NSM_LISTEN_ON","value":"tcp://:5006"},{"name":"NSM_PREFIX","value":"172.16.0.0/16"},{"name":"NSM_LOG_LEVEL","value":"TRACE"}],"image":"ghcr.io/networkservicemesh/cmd-ipam-vl3:v1.7.0-rc.2","imagePullPolicy":"IfNotPresent","name":"vl3-ipam","ports":[{"containerPort":5006,"hostPort":5006}],"resources":{"limits":{"cpu":"200m","memory":"40Mi"},"requests":{"cpu":"100m"}},"volumeMounts":[{"mountPath":"/run/spire/sockets","name":"spire-agent-socket"}]}],"volumes":[{"hostPath":{"path":"/run/spire/sockets","type":"Directory"},"name":"spire-agent-socket"},{"hostPath":{"path":"/var/lib/networkservicemesh","type":"DirectoryOrCreate"},"name":"nsm-socket"}]}}}}
    creationTimestamp: "2022-12-21T05:12:33Z"
    generation: 1
    labels:
      app: vl3-ipam
    name: vl3-ipam
    namespace: ns-dns-vl3
    resourceVersion: "3974"
    uid: ea108f9a-9b99-4824-9425-b8fce162efe3
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: vl3-ipam
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: vl3-ipam
          spiffe.io/spiffe-id: "true"
      spec:
        containers:
        - env:
          - name: SPIFFE_ENDPOINT_SOCKET
            value: unix:///run/spire/sockets/agent.sock
          - name: NSM_LISTEN_ON
            value: tcp://:5006
          - name: NSM_PREFIX
            value: 172.16.0.0/16
          - name: NSM_LOG_LEVEL
            value: TRACE
          image: ghcr.io/networkservicemesh/cmd-ipam-vl3:v1.7.0-rc.2
          imagePullPolicy: IfNotPresent
          name: vl3-ipam
          ports:
          - containerPort: 5006
            hostPort: 5006
            protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 40Mi
            requests:
              cpu: 100m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /run/spire/sockets
            name: spire-agent-socket
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /run/spire/sockets
            type: Directory
          name: spire-agent-socket
        - hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
          name: nsm-socket
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-12-21T05:13:00Z"
      lastUpdateTime: "2022-12-21T05:13:00Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-12-21T05:12:33Z"
      lastUpdateTime: "2022-12-21T05:13:00Z"
      message: ReplicaSet "vl3-ipam-7d564f85b" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: DeploymentList
metadata:
  resourceVersion: "19315"
