apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
        sidecar.istio.io/inject: "true"
      annotations:
        networkservicemesh.io: kernel://my-vl3-network/nsm-1?dnsName=ubuntu
    spec:
      containers:
        - name: ubuntu
          image: ubuntu
          command: ["sleep", "123456"]
          securityContext:
            privileged: true
