---
apiVersion: v1
items:
- metadata:
    creationTimestamp: "2022-12-22T00:10:08Z"
    generateName: nse-vl3-vpp-5d97745888-
    labels:
      app: nse-vl3-vpp
      pod-template-hash: 5d97745888
      spiffe.io/spiffe-id: "true"
    name: nse-vl3-vpp-5d97745888-5mf9c
    namespace: ns-dns-vl3
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: nse-vl3-vpp-5d97745888
      uid: 99cb7a66-8bde-48f2-b905-08cce49090fe
    resourceVersion: "5183"
    uid: 9c2dec25-6944-48c0-a8e8-ad5b8a406a0f
  spec:
    containers:
    - env:
      - name: NSM_SERVICE_NAMES
        value: my-vl3-network
      - name: NSM_REGISTER_SERVICE
        value: "true"
      - name: NSM_DNS_TEMPLATES
        value: '{{ index .Labels "dnsName" }}.{{ .NetworkService }}.'
      - name: SPIFFE_ENDPOINT_SOCKET
        value: unix:///run/spire/sockets/agent.sock
      - name: NSM_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: NSM_LOG_LEVEL
        value: TRACE
      image: ghcr.io/networkservicemesh/cmd-nse-vl3-vpp:v1.7.0-rc.2
      imagePullPolicy: IfNotPresent
      name: nse
      resources:
        limits:
          cpu: 500m
          memory: 400Mi
        requests:
          cpu: 150m
          memory: 400Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /run/spire/sockets
        name: spire-agent-socket
        readOnly: true
      - mountPath: /var/lib/networkservicemesh
        name: nsm-socket
        readOnly: true
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-mmk5b
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: kind-1-control-plane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - hostPath:
        path: /run/spire/sockets
        type: Directory
      name: spire-agent-socket
    - hostPath:
        path: /var/lib/networkservicemesh
        type: DirectoryOrCreate
      name: nsm-socket
    - name: kube-api-access-mmk5b
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-12-22T00:10:08Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-12-22T00:23:55Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-12-22T00:23:55Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-12-22T00:10:08Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://5554fe5f119d96f33f922d967c84ca74594fb5733054bcf24f5ea35504c76d66
      image: ghcr.io/networkservicemesh/cmd-nse-vl3-vpp:v1.7.0-rc.2
      imageID: ghcr.io/networkservicemesh/cmd-nse-vl3-vpp@sha256:c218c59e51ff3c2655bd8eb553b6abc7bda9ef0278c716eddf22751a11d38b40
      lastState:
        terminated:
          containerID: containerd://c395116c227cfca7118df6fcebe7cafa12bf8da05f3caebd59a6b81c56bfe570
          exitCode: 0
          finishedAt: "2022-12-22T00:23:42Z"
          reason: Completed
          startedAt: "2022-12-22T00:22:22Z"
      name: nse
      ready: true
      restartCount: 2
      started: true
      state:
        running:
          startedAt: "2022-12-22T00:23:55Z"
    hostIP: 172.18.0.2
    phase: Running
    podIP: 10.244.0.14
    podIPs:
    - ip: 10.244.0.14
    qosClass: Burstable
    startTime: "2022-12-22T00:10:08Z"
- metadata:
    creationTimestamp: "2022-12-22T00:10:08Z"
    generateName: vl3-ipam-7d564f85b-
    labels:
      app: vl3-ipam
      pod-template-hash: 7d564f85b
      spiffe.io/spiffe-id: "true"
    name: vl3-ipam-7d564f85b-4lfnn
    namespace: ns-dns-vl3
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: vl3-ipam-7d564f85b
      uid: 2041bae5-f9e1-42e5-830d-fbf07be908bd
    resourceVersion: "3255"
    uid: 815c6091-195c-4c48-a6f2-cd271d90a637
  spec:
    containers:
    - env:
      - name: SPIFFE_ENDPOINT_SOCKET
        value: unix:///run/spire/sockets/agent.sock
      - name: NSM_LISTEN_ON
        value: tcp://:5006
      - name: NSM_PREFIX
        value: 172.16.0.0/16
      - name: NSM_LOG_LEVEL
        value: TRACE
      image: ghcr.io/networkservicemesh/cmd-ipam-vl3:v1.7.0-rc.2
      imagePullPolicy: IfNotPresent
      name: vl3-ipam
      ports:
      - containerPort: 5006
        hostPort: 5006
        protocol: TCP
      resources:
        limits:
          cpu: 200m
          memory: 40Mi
        requests:
          cpu: 100m
          memory: 40Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /run/spire/sockets
        name: spire-agent-socket
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-cbp5s
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: kind-1-control-plane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - hostPath:
        path: /run/spire/sockets
        type: Directory
      name: spire-agent-socket
    - hostPath:
        path: /var/lib/networkservicemesh
        type: DirectoryOrCreate
      name: nsm-socket
    - name: kube-api-access-cbp5s
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-12-22T00:10:08Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-12-22T00:10:33Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-12-22T00:10:33Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-12-22T00:10:08Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://a7f978e8b11033e3939c5cd5c8b17d9e0cb2ef96224f61df9c97b103c11468fb
      image: ghcr.io/networkservicemesh/cmd-ipam-vl3:v1.7.0-rc.2
      imageID: ghcr.io/networkservicemesh/cmd-ipam-vl3@sha256:81d439a0437acfe1c29da2dfc176dc29774f50feec47e42ea2772ddec61e11a9
      lastState: {}
      name: vl3-ipam
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-12-22T00:10:32Z"
    hostIP: 172.18.0.2
    phase: Running
    podIP: 10.244.0.13
    podIPs:
    - ip: 10.244.0.13
    qosClass: Burstable
    startTime: "2022-12-22T00:10:08Z"
kind: PodList
metadata:
  resourceVersion: "5261"
