---
apiVersion: v1
items:
- metadata:
    annotations:
      prometheus.io/port: "15014"
      prometheus.io/scrape: "true"
      sidecar.istio.io/inject: "false"
    creationTimestamp: "2022-12-22T00:10:55Z"
    generateName: istiod-5d74c58fdd-
    labels:
      app: istiod
      install.operator.istio.io/owning-resource: unknown
      istio: pilot
      istio.io/rev: default
      operator.istio.io/component: Pilot
      pod-template-hash: 5d74c58fdd
      sidecar.istio.io/inject: "false"
      spiffe.io/spiffe-id: "true"
    name: istiod-5d74c58fdd-4pmbr
    namespace: istio-system
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: istiod-5d74c58fdd
      uid: d594fa5e-e675-46e8-bb00-1b1f9be392e2
    resourceVersion: "3477"
    uid: 9ec714ba-1304-411b-a476-8065c7295afc
  spec:
    containers:
    - args:
      - discovery
      - --monitoringAddr=:15014
      - --log_output_level=default:info
      - --domain
      - cluster.local
      - --keepaliveMaxServerConnectionAge
      - 30m
      env:
      - name: REVISION
        value: default
      - name: JWT_POLICY
        value: third-party-jwt
      - name: PILOT_CERT_PROVIDER
        value: istiod
      - name: POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      - name: SERVICE_ACCOUNT
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: spec.serviceAccountName
      - name: KUBECONFIG
        value: /var/run/secrets/remote/config
      - name: PILOT_TRACE_SAMPLING
        value: "1"
      - name: PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_OUTBOUND
        value: "true"
      - name: PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_INBOUND
        value: "true"
      - name: ISTIOD_ADDR
        value: istiod.istio-system.svc:15012
      - name: PILOT_ENABLE_ANALYSIS
        value: "false"
      - name: CLUSTER_ID
        value: Kubernetes
      image: docker.io/istio/pilot:1.16.0
      imagePullPolicy: IfNotPresent
      name: discovery
      ports:
      - containerPort: 8080
        protocol: TCP
      - containerPort: 15010
        protocol: TCP
      - containerPort: 15017
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /ready
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 1
        periodSeconds: 3
        successThreshold: 1
        timeoutSeconds: 5
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        runAsGroup: 1337
        runAsNonRoot: true
        runAsUser: 1337
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/tokens
        name: istio-token
        readOnly: true
      - mountPath: /var/run/secrets/istio-dns
        name: local-certs
      - mountPath: /etc/cacerts
        name: cacerts
        readOnly: true
      - mountPath: /var/run/secrets/remote
        name: istio-kubeconfig
        readOnly: true
      - mountPath: /var/run/secrets/istiod/tls
        name: istio-csr-dns-cert
        readOnly: true
      - mountPath: /var/run/secrets/istiod/ca
        name: istio-csr-ca-configmap
        readOnly: true
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-zlbbn
        readOnly: true
    - env:
      - name: NSM_LOG_LEVEL
        value: TRACE
      - name: SPIFFE_ENDPOINT_SOCKET
        value: unix:///run/spire/sockets/agent.sock
      - name: NSM_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: NSM_NETWORK_SERVICES
        value: kernel://my-vl3-network/nsm-1?dnsName=istio-cp
      image: ghcr.io/networkservicemesh/cmd-nsc:v1.7.0-rc.2
      imagePullPolicy: IfNotPresent
      name: cmd-nsc
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /run/spire/sockets
        name: spire-agent-socket
        readOnly: true
      - mountPath: /var/lib/networkservicemesh
        name: nsm-socket
        readOnly: true
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-zlbbn
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    initContainers:
    - env:
      - name: NSM_LOG_LEVEL
        value: TRACE
      - name: SPIFFE_ENDPOINT_SOCKET
        value: unix:///run/spire/sockets/agent.sock
      - name: NSM_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: NSM_NETWORK_SERVICES
        value: kernel://my-vl3-network/nsm-1?dnsName=istio-cp
      image: ghcr.io/networkservicemesh/cmd-nsc-init:v1.7.0-rc.2
      imagePullPolicy: IfNotPresent
      name: cmd-nsc-init
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /run/spire/sockets
        name: spire-agent-socket
        readOnly: true
      - mountPath: /var/lib/networkservicemesh
        name: nsm-socket
        readOnly: true
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-zlbbn
        readOnly: true
    nodeName: kind-1-control-plane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1337
    serviceAccount: istiod
    serviceAccountName: istiod
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - emptyDir:
        medium: Memory
      name: local-certs
    - name: istio-token
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            audience: istio-ca
            expirationSeconds: 43200
            path: istio-token
    - name: cacerts
      secret:
        defaultMode: 420
        optional: true
        secretName: cacerts
    - name: istio-kubeconfig
      secret:
        defaultMode: 420
        optional: true
        secretName: istio-kubeconfig
    - name: istio-csr-dns-cert
      secret:
        defaultMode: 420
        optional: true
        secretName: istiod-tls
    - configMap:
        defaultMode: 420
        name: istio-ca-root-cert
        optional: true
      name: istio-csr-ca-configmap
    - name: kube-api-access-zlbbn
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
    - hostPath:
        path: /run/spire/sockets
        type: Directory
      name: spire-agent-socket
    - hostPath:
        path: /var/lib/networkservicemesh
        type: Directory
      name: nsm-socket
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-12-22T00:11:06Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-12-22T00:11:28Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-12-22T00:11:28Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-12-22T00:10:55Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://f41c15c15d21996008afb5afeda96c4994e288f277637f41beba2e258a425d50
      image: ghcr.io/networkservicemesh/cmd-nsc:v1.7.0-rc.2
      imageID: ghcr.io/networkservicemesh/cmd-nsc@sha256:28bad4c7957cf62fc6637b5908904fe24768f24d24e6516c5e56209ab3a5b111
      lastState: {}
      name: cmd-nsc
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-12-22T00:11:28Z"
    - containerID: containerd://34358c1d7e616f4376dcb9e03ec7a4591dc88433e6b58cd9c2c30a3e8da8b4fe
      image: docker.io/istio/pilot:1.16.0
      imageID: docker.io/istio/pilot@sha256:ac0284d75ec9e6a73acaeb787881779ed27342c10fa5589d873dd30790a57868
      lastState: {}
      name: discovery
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-12-22T00:11:22Z"
    hostIP: 172.18.0.2
    initContainerStatuses:
    - containerID: containerd://a1079999b6e1eec1837bd11b59186b78642c8ea64e3aae6bcd59b56e6d68f01e
      image: ghcr.io/networkservicemesh/cmd-nsc-init:v1.7.0-rc.2
      imageID: ghcr.io/networkservicemesh/cmd-nsc-init@sha256:abc32416a4667f54d1bd8b2891d2d08d2fbce612211214d763c7301760555b52
      lastState: {}
      name: cmd-nsc-init
      ready: true
      restartCount: 0
      state:
        terminated:
          containerID: containerd://a1079999b6e1eec1837bd11b59186b78642c8ea64e3aae6bcd59b56e6d68f01e
          exitCode: 0
          finishedAt: "2022-12-22T00:11:05Z"
          reason: Completed
          startedAt: "2022-12-22T00:11:01Z"
    phase: Running
    podIP: 10.244.0.15
    podIPs:
    - ip: 10.244.0.15
    qosClass: Burstable
    startTime: "2022-12-22T00:10:55Z"
kind: PodList
metadata:
  resourceVersion: "5253"
