---
apiVersion: v1
kind: Service
metadata:
  name: nsmgr-proxy
spec:
  selector:
    app: nsmgr-proxy
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
      nodePort: 30004
  type: LoadBalancer
