---
apiVersion: apps/v1
items:
- metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2022-12-21T04:34:21Z"
    generation: 1
    labels:
      app: admission-webhook-k8s
      pod-template-hash: 688dfc7685
    name: admission-webhook-k8s-688dfc7685
    namespace: nsm-system
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: admission-webhook-k8s
      uid: 1a483632-156b-496f-9507-9662b9596fe3
    resourceVersion: "984"
    uid: aa36d050-002a-4337-ba06-41c7f01cc874
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: admission-webhook-k8s
        pod-template-hash: 688dfc7685
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: admission-webhook-k8s
          pod-template-hash: 688dfc7685
      spec:
        containers:
        - env:
          - name: SPIFFE_ENDPOINT_SOCKET
            value: unix:///run/spire/sockets/agent.sock
          - name: NSM_SERVICE_NAME
            value: admission-webhook-svc
          - name: NSM_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: NSM_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: NSM_ANNOTATION
            value: networkservicemesh.io
          - name: NSM_CONTAINER_IMAGES
            value: ghcr.io/networkservicemesh/cmd-nsc:v1.7.0-rc.2
          - name: NSM_INIT_CONTAINER_IMAGES
            value: ghcr.io/networkservicemesh/cmd-nsc-init:v1.7.0-rc.2
          - name: NSM_LABELS
            value: spiffe.io/spiffe-id:true
          - name: NSM_ENVS
            value: NSM_LOG_LEVEL=TRACE
          image: ghcr.io/networkservicemesh/cmd-admission-webhook-k8s:v1.7.0-rc.2
          imagePullPolicy: IfNotPresent
          name: admission-webhook-k8s
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 443
              scheme: HTTPS
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: admission-webhook-sa
        serviceAccountName: admission-webhook-sa
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
- metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2022-12-21T04:34:21Z"
    generation: 1
    labels:
      app: nsmgr-proxy
      pod-template-hash: c874d5d87
      spiffe.io/spiffe-id: "true"
    name: nsmgr-proxy-c874d5d87
    namespace: nsm-system
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: nsmgr-proxy
      uid: 9fcd1fad-0dce-4d36-994e-2f7ab22c2c49
    resourceVersion: "1149"
    uid: ecf39949-7b04-4dc3-b7df-6a1ed95d3ebb
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: nsmgr-proxy
        pod-template-hash: c874d5d87
    template:
      metadata:
        annotations:
          spiffe.io/federatesWith: nsm.cluster2
        creationTimestamp: null
        labels:
          app: nsmgr-proxy
          pod-template-hash: c874d5d87
          spiffe.io/spiffe-id: "true"
      spec:
        containers:
        - env:
          - name: SPIFFE_ENDPOINT_SOCKET
            value: unix:///run/spire/sockets/agent.sock
          - name: NSM_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: NSM_LOG_LEVEL
            value: TRACE
          - name: NSM_REGISTRY_URL
            value: registry:5002
          - name: NSM_REGISTRY_PROXY_URL
            value: registry-proxy:5005
          - name: NSM_LISTEN_ON
            value: tcp://:5004
          - name: NSM_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: NSM_MAP_IP_FILE_PATH
            value: /etc/mapip/config.yaml
          image: ghcr.io/networkservicemesh/cmd-nsmgr-proxy:v1.7.0-rc.2
          imagePullPolicy: IfNotPresent
          name: nsmgr-proxy
          ports:
          - containerPort: 5004
            hostPort: 5004
            protocol: TCP
          resources:
            limits:
              cpu: 400m
              memory: 100Mi
            requests:
              cpu: 200m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /run/spire/sockets
            name: spire-agent-socket
            readOnly: true
          - mountPath: /etc/mapip
            name: mapip-volume
        - env:
          - name: NSM_OUTPUTPATH
            value: /etc/mapip/config.yaml
          - name: NSM_NODENAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          image: ghcr.io/networkservicemesh/cmd-map-ip-k8s:v1.7.0-rc.2
          imagePullPolicy: IfNotPresent
          name: map-ip-k8s
          resources:
            limits:
              cpu: 50m
              memory: 25Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/mapip
            name: mapip-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: nsmgr-proxy-sa
        serviceAccountName: nsmgr-proxy-sa
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /run/spire/sockets
            type: Directory
          name: spire-agent-socket
        - hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
          name: nsm-socket
        - emptyDir: {}
          name: mapip-volume
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
- metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2022-12-21T04:34:21Z"
    generation: 1
    labels:
      app: registry
      pod-template-hash: 679b68767c
      spiffe.io/spiffe-id: "true"
    name: registry-k8s-679b68767c
    namespace: nsm-system
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: registry-k8s
      uid: 379403df-3a70-45cc-9a7c-1ffbdad66b86
    resourceVersion: "1006"
    uid: 7246b2ab-4ee7-4764-84db-0babeacbd72b
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: registry
        pod-template-hash: 679b68767c
    template:
      metadata:
        annotations:
          spiffe.io/federatesWith: nsm.cluster2
        creationTimestamp: null
        labels:
          app: registry
          pod-template-hash: 679b68767c
          spiffe.io/spiffe-id: "true"
      spec:
        containers:
        - env:
          - name: SPIFFE_ENDPOINT_SOCKET
            value: unix:///run/spire/sockets/agent.sock
          - name: REGISTRY_K8S_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: REGISTRY_K8S_LOG_LEVEL
            value: TRACE
          - name: REGISTRY_K8S_LISTEN_ON
            value: tcp://:5002
          - name: REGISTRY_K8S_PROXY_REGISTRY_URL
            value: nsmgr-proxy:5004
          image: ghcr.io/networkservicemesh/cmd-registry-k8s:v1.7.0-rc.2
          imagePullPolicy: IfNotPresent
          name: registry
          ports:
          - containerPort: 5002
            hostPort: 5002
            protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 40Mi
            requests:
              cpu: 100m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /run/spire/sockets
            name: spire-agent-socket
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: registry-k8s-sa
        serviceAccountName: registry-k8s-sa
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /run/spire/sockets
            type: Directory
          name: spire-agent-socket
        - hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
          name: nsm-socket
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
- metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2022-12-21T04:34:21Z"
    generation: 1
    labels:
      app: registry-proxy
      pod-template-hash: 5d4487556b
      spiffe.io/spiffe-id: "true"
    name: registry-proxy-5d4487556b
    namespace: nsm-system
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: registry-proxy
      uid: 4bd580c4-6393-4174-9924-29e4a943f513
    resourceVersion: "1024"
    uid: 6ea0527c-0748-4a6b-b67c-2e8dea7df31d
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: registry-proxy
        pod-template-hash: 5d4487556b
    template:
      metadata:
        annotations:
          spiffe.io/federatesWith: nsm.cluster2
        creationTimestamp: null
        labels:
          app: registry-proxy
          pod-template-hash: 5d4487556b
          spiffe.io/spiffe-id: "true"
      spec:
        containers:
        - env:
          - name: SPIFFE_ENDPOINT_SOCKET
            value: unix:///run/spire/sockets/agent.sock
          - name: NSM_LISTEN_ON
            value: tcp://:5005
          - name: NSM_LOG_LEVEL
            value: TRACE
          image: ghcr.io/networkservicemesh/cmd-registry-proxy-dns:v1.7.0-rc.2
          imagePullPolicy: IfNotPresent
          name: registry
          ports:
          - containerPort: 5005
            hostPort: 5005
            protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 40Mi
            requests:
              cpu: 100m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /run/spire/sockets
            name: spire-agent-socket
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /run/spire/sockets
            type: Directory
          name: spire-agent-socket
        - hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
          name: nsm-socket
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
kind: ReplicaSetList
metadata:
  resourceVersion: "19317"
