---
apiVersion: v1
items:
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T23:38:40Z"
  involvedObject:
    apiVersion: v1
    kind: Pod
    name: controller-6658b8446c-m7kds
    namespace: metallb-system
    resourceVersion: "478"
    uid: 2dca40a1-0a8c-4a20-a83f-b8ee24e54a54
  lastTimestamp: "2022-12-21T23:38:40Z"
  message: Successfully assigned metallb-system/controller-6658b8446c-m7kds to kind-1-control-plane
  metadata:
    creationTimestamp: "2022-12-21T23:38:40Z"
    name: controller-6658b8446c-m7kds.1732f34c315ea520
    namespace: metallb-system
    resourceVersion: "486"
    uid: 107d0901-c748-4436-b88a-f64fb76cbcb7
  reason: Scheduled
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: default-scheduler
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T23:38:40Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{controller}
    kind: Pod
    name: controller-6658b8446c-m7kds
    namespace: metallb-system
    resourceVersion: "484"
    uid: 2dca40a1-0a8c-4a20-a83f-b8ee24e54a54
  lastTimestamp: "2022-12-21T23:38:40Z"
  message: Pulling image "quay.io/metallb/controller:v0.12.1"
  metadata:
    creationTimestamp: "2022-12-21T23:38:40Z"
    name: controller-6658b8446c-m7kds.1732f34c4b3f0190
    namespace: metallb-system
    resourceVersion: "493"
    uid: a16bd4f1-394c-4a18-9cda-0b26e0725f36
  reason: Pulling
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T23:38:51Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{controller}
    kind: Pod
    name: controller-6658b8446c-m7kds
    namespace: metallb-system
    resourceVersion: "484"
    uid: 2dca40a1-0a8c-4a20-a83f-b8ee24e54a54
  lastTimestamp: "2022-12-21T23:38:51Z"
  message: Successfully pulled image "quay.io/metallb/controller:v0.12.1" in 10.47279609s
  metadata:
    creationTimestamp: "2022-12-21T23:38:51Z"
    name: controller-6658b8446c-m7kds.1732f34ebb7f97f8
    namespace: metallb-system
    resourceVersion: "511"
    uid: cc11f8ba-dd53-44dd-a85b-5a8e6ffcbe18
  reason: Pulled
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T23:38:51Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{controller}
    kind: Pod
    name: controller-6658b8446c-m7kds
    namespace: metallb-system
    resourceVersion: "484"
    uid: 2dca40a1-0a8c-4a20-a83f-b8ee24e54a54
  lastTimestamp: "2022-12-21T23:38:51Z"
  message: Created container controller
  metadata:
    creationTimestamp: "2022-12-21T23:38:51Z"
    name: controller-6658b8446c-m7kds.1732f34ebc4638a6
    namespace: metallb-system
    resourceVersion: "512"
    uid: aebedd9e-8cf7-4c85-b73b-febc667e66c1
  reason: Created
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T23:38:51Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{controller}
    kind: Pod
    name: controller-6658b8446c-m7kds
    namespace: metallb-system
    resourceVersion: "484"
    uid: 2dca40a1-0a8c-4a20-a83f-b8ee24e54a54
  lastTimestamp: "2022-12-21T23:38:51Z"
  message: Started container controller
  metadata:
    creationTimestamp: "2022-12-21T23:38:51Z"
    name: controller-6658b8446c-m7kds.1732f34ecefe2208
    namespace: metallb-system
    resourceVersion: "513"
    uid: 9360c362-015a-4005-87af-df59b3a23dde
  reason: Started
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T23:38:40Z"
  involvedObject:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: controller-6658b8446c
    namespace: metallb-system
    resourceVersion: "475"
    uid: 664c3921-39a6-42a0-87cb-6d2200330e43
  lastTimestamp: "2022-12-21T23:38:40Z"
  message: 'Created pod: controller-6658b8446c-m7kds'
  metadata:
    creationTimestamp: "2022-12-21T23:38:40Z"
    name: controller-6658b8446c.1732f34c308fcc17
    namespace: metallb-system
    resourceVersion: "482"
    uid: d119923b-12dc-4bbc-bd38-8a78f294ba4d
  reason: SuccessfulCreate
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: replicaset-controller
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T23:38:40Z"
  involvedObject:
    apiVersion: apps/v1
    kind: Deployment
    name: controller
    namespace: metallb-system
    resourceVersion: "472"
    uid: 90963ed9-bd54-4d1a-abd3-0e00e0bf66a4
  lastTimestamp: "2022-12-21T23:38:40Z"
  message: Scaled up replica set controller-6658b8446c to 1
  metadata:
    creationTimestamp: "2022-12-21T23:38:40Z"
    name: controller.1732f34c303e6015
    namespace: metallb-system
    resourceVersion: "480"
    uid: 64ec92a5-ac61-405d-af97-edb57e184224
  reason: ScalingReplicaSet
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: deployment-controller
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T23:38:40Z"
  involvedObject:
    apiVersion: v1
    kind: Pod
    name: speaker-kzw6c
    namespace: metallb-system
    resourceVersion: "471"
    uid: 48468628-0fe8-4d60-a407-99a561388f38
  lastTimestamp: "2022-12-21T23:38:40Z"
  message: Successfully assigned metallb-system/speaker-kzw6c to kind-1-control-plane
  metadata:
    creationTimestamp: "2022-12-21T23:38:40Z"
    name: speaker-kzw6c.1732f34c2e7e5b76
    namespace: metallb-system
    resourceVersion: "476"
    uid: 47b53bc4-5f81-49fb-8709-1d6496f07526
  reason: Scheduled
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: default-scheduler
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T23:38:40Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{speaker}
    kind: Pod
    name: speaker-kzw6c
    namespace: metallb-system
    resourceVersion: "473"
    uid: 48468628-0fe8-4d60-a407-99a561388f38
  lastTimestamp: "2022-12-21T23:38:40Z"
  message: Pulling image "quay.io/metallb/speaker:v0.12.1"
  metadata:
    creationTimestamp: "2022-12-21T23:38:40Z"
    name: speaker-kzw6c.1732f34c48636052
    namespace: metallb-system
    resourceVersion: "492"
    uid: a863d289-b471-410f-9d8f-fef0d46c6de3
  reason: Pulling
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T23:38:46Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{speaker}
    kind: Pod
    name: speaker-kzw6c
    namespace: metallb-system
    resourceVersion: "473"
    uid: 48468628-0fe8-4d60-a407-99a561388f38
  lastTimestamp: "2022-12-21T23:38:46Z"
  message: Successfully pulled image "quay.io/metallb/speaker:v0.12.1" in 6.055881674s
  metadata:
    creationTimestamp: "2022-12-21T23:38:46Z"
    name: speaker-kzw6c.1732f34db158fa01
    namespace: metallb-system
    resourceVersion: "501"
    uid: 4d87f7d4-626b-4882-a0d8-568a941d0b85
  reason: Pulled
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 2
  eventTime: null
  firstTimestamp: "2022-12-21T23:38:46Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{speaker}
    kind: Pod
    name: speaker-kzw6c
    namespace: metallb-system
    resourceVersion: "473"
    uid: 48468628-0fe8-4d60-a407-99a561388f38
  lastTimestamp: "2022-12-21T23:38:47Z"
  message: 'Error: secret "memberlist" not found'
  metadata:
    creationTimestamp: "2022-12-21T23:38:46Z"
    name: speaker-kzw6c.1732f34db15ac907
    namespace: metallb-system
    resourceVersion: "505"
    uid: 214bc34c-8496-4686-a8a1-fc04a31de535
  reason: Failed
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Warning
- count: 2
  eventTime: null
  firstTimestamp: "2022-12-21T23:38:47Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{speaker}
    kind: Pod
    name: speaker-kzw6c
    namespace: metallb-system
    resourceVersion: "473"
    uid: 48468628-0fe8-4d60-a407-99a561388f38
  lastTimestamp: "2022-12-21T23:38:58Z"
  message: Container image "quay.io/metallb/speaker:v0.12.1" already present on machine
  metadata:
    creationTimestamp: "2022-12-21T23:38:47Z"
    name: speaker-kzw6c.1732f34dccf68496
    namespace: metallb-system
    resourceVersion: "524"
    uid: f03ddef9-25ab-4993-8fb4-a8b47ef5d0e3
  reason: Pulled
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T23:38:58Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{speaker}
    kind: Pod
    name: speaker-kzw6c
    namespace: metallb-system
    resourceVersion: "473"
    uid: 48468628-0fe8-4d60-a407-99a561388f38
  lastTimestamp: "2022-12-21T23:38:58Z"
  message: Created container speaker
  metadata:
    creationTimestamp: "2022-12-21T23:38:58Z"
    name: speaker-kzw6c.1732f3505f5358d3
    namespace: metallb-system
    resourceVersion: "526"
    uid: 928a5ab6-db9f-4e5b-bc32-6414303b59e0
  reason: Created
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T23:38:58Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{speaker}
    kind: Pod
    name: speaker-kzw6c
    namespace: metallb-system
    resourceVersion: "473"
    uid: 48468628-0fe8-4d60-a407-99a561388f38
  lastTimestamp: "2022-12-21T23:38:58Z"
  message: Started container speaker
  metadata:
    creationTimestamp: "2022-12-21T23:38:58Z"
    name: speaker-kzw6c.1732f35064d4e127
    namespace: metallb-system
    resourceVersion: "527"
    uid: b8f586a8-fcf4-40b8-a08b-696f1d346242
  reason: Started
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: kind-1-control-plane
  type: Normal
- count: 1
  eventTime: null
  firstTimestamp: "2022-12-21T23:38:40Z"
  involvedObject:
    apiVersion: apps/v1
    kind: DaemonSet
    name: speaker
    namespace: metallb-system
    resourceVersion: "469"
    uid: f3d64c96-28f7-4e31-b960-c867927fbf3b
  lastTimestamp: "2022-12-21T23:38:40Z"
  message: 'Created pod: speaker-kzw6c'
  metadata:
    creationTimestamp: "2022-12-21T23:38:40Z"
    name: speaker.1732f34c2dff2367
    namespace: metallb-system
    resourceVersion: "474"
    uid: 2d2f0602-2ebd-4e19-bfff-9ea0e523c45b
  reason: SuccessfulCreate
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: daemonset-controller
  type: Normal
kind: EventList
metadata:
  resourceVersion: "5259"
