---
apiVersion: apps/v1
items:
- metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"ubuntu"},"name":"ubuntu-deployment","namespace":"vl3-test"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"ubuntu"}},"strategy":{},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/default-container":"ubuntu","kubectl.kubernetes.io/default-logs-container":"ubuntu","networkservicemesh.io":"kernel://my-vl3-network/nsm-1?dnsName=ubuntu","prometheus.io/path":"/stats/prometheus","prometheus.io/port":"15020","prometheus.io/scrape":"true","sidecar.istio.io/status":"{\"initContainers\":[\"istio-init\"],\"containers\":[\"istio-proxy\"],\"volumes\":[\"workload-socket\",\"credential-socket\",\"workload-certs\",\"istio-envoy\",\"istio-data\",\"istio-podinfo\",\"istio-token\",\"istiod-ca-cert\"],\"imagePullSecrets\":null,\"revision\":\"default\"}"},"creationTimestamp":null,"labels":{"app":"ubuntu","security.istio.io/tlsMode":"istio","service.istio.io/canonical-name":"ubuntu","service.istio.io/canonical-revision":"latest"}},"spec":{"containers":[{"command":["sleep","123456"],"image":"ubuntu","name":"ubuntu","resources":{},"securityContext":{"privileged":true}},{"args":["proxy","sidecar","--domain","","--proxyLogLevel=warning","--proxyComponentLogLevel=misc:error","--log_output_level=default:info","--concurrency","2"],"env":[{"name":"JWT_POLICY","value":"third-party-jwt"},{"name":"PILOT_CERT_PROVIDER","value":"istiod"},{"name":"CA_ADDR","value":"istiod.istio-system.svc:15012"},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"POD_NAMESPACE","value":"vm-ns"},{"name":"INSTANCE_IP","valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}},{"name":"SERVICE_ACCOUNT","value":"serviceaccountvm"},{"name":"HOST_IP","valueFrom":{"fieldRef":{"fieldPath":"status.hostIP"}}},{"name":"PROXY_CONFIG","value":"{}\n"},{"name":"ISTIO_META_POD_PORTS","value":"[\n]"},{"name":"ISTIO_META_APP_CONTAINERS","value":"ubuntu"},{"name":"ISTIO_META_CLUSTER_ID","value":"Kubernetes"},{"name":"ISTIO_META_INTERCEPTION_MODE","value":"REDIRECT"},{"name":"ISTIO_META_MESH_ID","value":"cluster.local"},{"name":"TRUST_DOMAIN","value":"cluster.local"}],"image":"docker.io/istio/proxyv2:1.16.0","name":"istio-proxy","ports":[{"containerPort":15090,"name":"http-envoy-prom","protocol":"TCP"}],"readinessProbe":{"failureThreshold":30,"httpGet":{"path":"/healthz/ready","port":15021},"initialDelaySeconds":1,"periodSeconds":2,"timeoutSeconds":3},"resources":{"limits":{"cpu":"2","memory":"1Gi"},"requests":{"cpu":"100m","memory":"128Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":true,"runAsGroup":1337,"runAsNonRoot":true,"runAsUser":1337},"volumeMounts":[{"mountPath":"/var/run/secrets/istio/root-cert.pem","name":"cert","subPath":"root-cert.pem"},{"mountPath":"/var/lib/istio/envoy/cluster.env","name":"cert","subPath":"cluster.env"},{"mountPath":"/etc/istio/config/mesh","name":"cert","subPath":"mesh.yaml"},{"mountPath":"/var/run/secrets/tokens/istio-token","name":"cert","subPath":"istio-token"},{"mountPath":"/var/run/secrets/workload-spiffe-uds","name":"workload-socket"},{"mountPath":"/var/run/secrets/credential-uds","name":"credential-socket"},{"mountPath":"/var/run/secrets/workload-spiffe-credentials","name":"workload-certs"},{"mountPath":"/var/lib/istio/data","name":"istio-data"},{"mountPath":"/etc/istio/proxy","name":"istio-envoy"}]}],"hostAliases":[{"hostnames":["istiod.istio-system.svc"],"ip":"172.16.0.2"}],"initContainers":[{"args":["istio-iptables","-p","15001","-z","15006","-u","1337","-m","REDIRECT","-i","*","-x","","-b","*","-d","15090,15021,15020","--log_output_level=default:info"],"image":"docker.io/istio/proxyv2:1.16.0","name":"istio-init","resources":{"limits":{"cpu":"2","memory":"1Gi"},"requests":{"cpu":"100m","memory":"128Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"add":["NET_ADMIN","NET_RAW"],"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":false,"runAsGroup":0,"runAsNonRoot":false,"runAsUser":0}}],"volumes":[{"configMap":{"name":"cert-file"},"name":"cert"},{"name":"workload-socket"},{"name":"credential-socket"},{"name":"workload-certs"},{"emptyDir":{"medium":"Memory"},"name":"istio-envoy"},{"emptyDir":{},"name":"istio-data"}]}}},"status":{}}
    creationTimestamp: "2022-12-22T00:23:20Z"
    generation: 1
    labels:
      app: ubuntu
    name: ubuntu-deployment
    namespace: vl3-test
    resourceVersion: "5078"
    uid: 90854250-e27c-47f1-9ff9-62a9a74acfa7
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: ubuntu
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/default-container: ubuntu
          kubectl.kubernetes.io/default-logs-container: ubuntu
          networkservicemesh.io: kernel://my-vl3-network/nsm-1?dnsName=ubuntu
          prometheus.io/path: /stats/prometheus
          prometheus.io/port: "15020"
          prometheus.io/scrape: "true"
          sidecar.istio.io/status: '{"initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["workload-socket","credential-socket","workload-certs","istio-envoy","istio-data","istio-podinfo","istio-token","istiod-ca-cert"],"imagePullSecrets":null,"revision":"default"}'
        creationTimestamp: null
        labels:
          app: ubuntu
          security.istio.io/tlsMode: istio
          service.istio.io/canonical-name: ubuntu
          service.istio.io/canonical-revision: latest
      spec:
        containers:
        - command:
          - sleep
          - "123456"
          image: ubuntu
          imagePullPolicy: Always
          name: ubuntu
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - args:
          - proxy
          - sidecar
          - --domain
          - ""
          - --proxyLogLevel=warning
          - --proxyComponentLogLevel=misc:error
          - --log_output_level=default:info
          - --concurrency
          - "2"
          env:
          - name: JWT_POLICY
            value: third-party-jwt
          - name: PILOT_CERT_PROVIDER
            value: istiod
          - name: CA_ADDR
            value: istiod.istio-system.svc:15012
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            value: vm-ns
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: SERVICE_ACCOUNT
            value: serviceaccountvm
          - name: HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: PROXY_CONFIG
            value: |
              {}
          - name: ISTIO_META_POD_PORTS
            value: |-
              [
              ]
          - name: ISTIO_META_APP_CONTAINERS
            value: ubuntu
          - name: ISTIO_META_CLUSTER_ID
            value: Kubernetes
          - name: ISTIO_META_INTERCEPTION_MODE
            value: REDIRECT
          - name: ISTIO_META_MESH_ID
            value: cluster.local
          - name: TRUST_DOMAIN
            value: cluster.local
          image: docker.io/istio/proxyv2:1.16.0
          imagePullPolicy: IfNotPresent
          name: istio-proxy
          ports:
          - containerPort: 15090
            name: http-envoy-prom
            protocol: TCP
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /healthz/ready
              port: 15021
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1337
            runAsNonRoot: true
            runAsUser: 1337
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/run/secrets/istio/root-cert.pem
            name: cert
            subPath: root-cert.pem
          - mountPath: /var/lib/istio/envoy/cluster.env
            name: cert
            subPath: cluster.env
          - mountPath: /etc/istio/config/mesh
            name: cert
            subPath: mesh.yaml
          - mountPath: /var/run/secrets/tokens/istio-token
            name: cert
            subPath: istio-token
          - mountPath: /var/run/secrets/workload-spiffe-uds
            name: workload-socket
          - mountPath: /var/run/secrets/credential-uds
            name: credential-socket
          - mountPath: /var/run/secrets/workload-spiffe-credentials
            name: workload-certs
          - mountPath: /var/lib/istio/data
            name: istio-data
          - mountPath: /etc/istio/proxy
            name: istio-envoy
        dnsPolicy: ClusterFirst
        hostAliases:
        - hostnames:
          - istiod.istio-system.svc
          ip: 172.16.0.2
        initContainers:
        - args:
          - istio-iptables
          - -p
          - "15001"
          - -z
          - "15006"
          - -u
          - "1337"
          - -m
          - REDIRECT
          - -i
          - '*'
          - -x
          - ""
          - -b
          - '*'
          - -d
          - 15090,15021,15020
          - --log_output_level=default:info
          image: docker.io/istio/proxyv2:1.16.0
          imagePullPolicy: IfNotPresent
          name: istio-init
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
              - NET_ADMIN
              - NET_RAW
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: cert-file
          name: cert
        - emptyDir: {}
          name: workload-socket
        - emptyDir: {}
          name: credential-socket
        - emptyDir: {}
          name: workload-certs
        - emptyDir:
            medium: Memory
          name: istio-envoy
        - emptyDir: {}
          name: istio-data
  status:
    conditions:
    - lastTransitionTime: "2022-12-22T00:23:20Z"
      lastUpdateTime: "2022-12-22T00:23:20Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2022-12-22T00:23:20Z"
      lastUpdateTime: "2022-12-22T00:23:20Z"
      message: ReplicaSet "ubuntu-deployment-584577c947" is progressing.
      reason: ReplicaSetUpdated
      status: "True"
      type: Progressing
    observedGeneration: 1
    replicas: 1
    unavailableReplicas: 1
    updatedReplicas: 1
kind: DeploymentList
metadata:
  resourceVersion: "5267"
