---
apiVersion: apps/v1
items:
- metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"networkservicemesh.io":"kernel://my-vl3-network/nsm-1?dnsName=helloworld"},"labels":{"app":"helloworld","version":"v1"},"name":"helloworld-v1","namespace":"sample"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"helloworld","version":"v1"}},"template":{"metadata":{"labels":{"app":"helloworld","version":"v1"}},"spec":{"containers":[{"image":"docker.io/istio/examples-helloworld-v1","imagePullPolicy":"IfNotPresent","name":"helloworld","ports":[{"containerPort":80},{"containerPort":5000}],"resources":{"requests":{"cpu":"100m"}}}]}}}}
      networkservicemesh.io: kernel://my-vl3-network/nsm-1?dnsName=helloworld
    creationTimestamp: "2022-12-23T13:30:17Z"
    generation: 1
    labels:
      app: helloworld
      version: v1
    name: helloworld-v1
    namespace: sample
    resourceVersion: "2185"
    uid: 47b82c0e-e8b7-4b6b-8d99-9e48c337fee7
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: helloworld
        version: v1
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: helloworld
          spiffe.io/spiffe-id: "true"
          version: v1
      spec:
        containers:
        - image: docker.io/istio/examples-helloworld-v1
          imagePullPolicy: IfNotPresent
          name: helloworld
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 5000
            protocol: TCP
          resources:
            requests:
              cpu: 100m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - env:
          - name: NSM_LOG_LEVEL
            value: TRACE
          - name: SPIFFE_ENDPOINT_SOCKET
            value: unix:///run/spire/sockets/agent.sock
          - name: NSM_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: NSM_NETWORK_SERVICES
            value: kernel://my-vl3-network/nsm-1?dnsName=helloworld
          image: ghcr.io/networkservicemesh/cmd-nsc:v1.7.0-rc.2
          imagePullPolicy: IfNotPresent
          name: cmd-nsc
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /run/spire/sockets
            name: spire-agent-socket
            readOnly: true
          - mountPath: /var/lib/networkservicemesh
            name: nsm-socket
            readOnly: true
        dnsPolicy: ClusterFirst
        initContainers:
        - env:
          - name: NSM_LOG_LEVEL
            value: TRACE
          - name: SPIFFE_ENDPOINT_SOCKET
            value: unix:///run/spire/sockets/agent.sock
          - name: NSM_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: NSM_NETWORK_SERVICES
            value: kernel://my-vl3-network/nsm-1?dnsName=helloworld
          image: ghcr.io/networkservicemesh/cmd-nsc-init:v1.7.0-rc.2
          imagePullPolicy: IfNotPresent
          name: cmd-nsc-init
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /run/spire/sockets
            name: spire-agent-socket
            readOnly: true
          - mountPath: /var/lib/networkservicemesh
            name: nsm-socket
            readOnly: true
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /run/spire/sockets
            type: Directory
          name: spire-agent-socket
        - hostPath:
            path: /var/lib/networkservicemesh
            type: Directory
          name: nsm-socket
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-12-23T13:31:27Z"
      lastUpdateTime: "2022-12-23T13:31:27Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-12-23T13:30:17Z"
      lastUpdateTime: "2022-12-23T13:31:27Z"
      message: ReplicaSet "helloworld-v1-5c59cf7d49" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: DeploymentList
metadata:
  resourceVersion: "3083"
