---
apiVersion: v1
items:
- metadata:
    annotations:
      kubectl.kubernetes.io/default-container: helloworld
      kubectl.kubernetes.io/default-logs-container: helloworld
      prometheus.io/path: /stats/prometheus
      prometheus.io/port: "15020"
      prometheus.io/scrape: "true"
      sidecar.istio.io/status: '{"initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["workload-socket","credential-socket","workload-certs","istio-envoy","istio-data","istio-podinfo","istio-token","istiod-ca-cert"],"imagePullSecrets":null,"revision":"default"}'
    creationTimestamp: "2022-12-23T13:30:17Z"
    generateName: helloworld-v1-5c59cf7d49-
    labels:
      app: helloworld
      pod-template-hash: 5c59cf7d49
      security.istio.io/tlsMode: istio
      service.istio.io/canonical-name: helloworld
      service.istio.io/canonical-revision: v1
      spiffe.io/spiffe-id: "true"
      version: v1
    name: helloworld-v1-5c59cf7d49-cgqv7
    namespace: sample
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: helloworld-v1-5c59cf7d49
      uid: a94d6648-6598-4e93-bac3-91b77a0256de
    resourceVersion: "2181"
    uid: 1b30d329-12db-4392-9017-d2986ccf5334
  spec:
    containers:
    - image: docker.io/istio/examples-helloworld-v1
      imagePullPolicy: IfNotPresent
      name: helloworld
      ports:
      - containerPort: 80
        protocol: TCP
      - containerPort: 5000
        protocol: TCP
      resources:
        requests:
          cpu: 100m
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-lv847
        readOnly: true
    - env:
      - name: NSM_LOG_LEVEL
        value: TRACE
      - name: SPIFFE_ENDPOINT_SOCKET
        value: unix:///run/spire/sockets/agent.sock
      - name: NSM_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: NSM_NETWORK_SERVICES
        value: kernel://my-vl3-network/nsm-1?dnsName=helloworld
      image: ghcr.io/networkservicemesh/cmd-nsc:v1.7.0-rc.2
      imagePullPolicy: IfNotPresent
      name: cmd-nsc
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /run/spire/sockets
        name: spire-agent-socket
        readOnly: true
      - mountPath: /var/lib/networkservicemesh
        name: nsm-socket
        readOnly: true
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-lv847
        readOnly: true
    - args:
      - proxy
      - sidecar
      - --domain
      - $(POD_NAMESPACE).svc.cluster.local
      - --proxyLogLevel=warning
      - --proxyComponentLogLevel=misc:error
      - --log_output_level=default:info
      - --concurrency
      - "2"
      env:
      - name: JWT_POLICY
        value: third-party-jwt
      - name: PILOT_CERT_PROVIDER
        value: istiod
      - name: CA_ADDR
        value: istiod.istio-system.svc:15012
      - name: POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      - name: INSTANCE_IP
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.podIP
      - name: SERVICE_ACCOUNT
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: spec.serviceAccountName
      - name: HOST_IP
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.hostIP
      - name: PROXY_CONFIG
        value: |
          {}
      - name: ISTIO_META_POD_PORTS
        value: |-
          [
              {"containerPort":80,"protocol":"TCP"}
              ,{"containerPort":5000,"protocol":"TCP"}
          ]
      - name: ISTIO_META_APP_CONTAINERS
        value: helloworld,cmd-nsc
      - name: ISTIO_META_CLUSTER_ID
        value: Kubernetes
      - name: ISTIO_META_INTERCEPTION_MODE
        value: REDIRECT
      - name: ISTIO_META_WORKLOAD_NAME
        value: helloworld-v1
      - name: ISTIO_META_OWNER
        value: kubernetes://apis/apps/v1/namespaces/sample/deployments/helloworld-v1
      - name: ISTIO_META_MESH_ID
        value: cluster.local
      - name: TRUST_DOMAIN
        value: cluster.local
      image: docker.io/istio/proxyv2:1.16.0
      imagePullPolicy: IfNotPresent
      name: istio-proxy
      ports:
      - containerPort: 15090
        name: http-envoy-prom
        protocol: TCP
      readinessProbe:
        failureThreshold: 30
        httpGet:
          path: /healthz/ready
          port: 15021
          scheme: HTTP
        initialDelaySeconds: 1
        periodSeconds: 2
        successThreshold: 1
        timeoutSeconds: 3
      resources:
        limits:
          cpu: "2"
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsGroup: 1337
        runAsNonRoot: true
        runAsUser: 1337
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/workload-spiffe-uds
        name: workload-socket
      - mountPath: /var/run/secrets/credential-uds
        name: credential-socket
      - mountPath: /var/run/secrets/workload-spiffe-credentials
        name: workload-certs
      - mountPath: /var/run/secrets/istio
        name: istiod-ca-cert
      - mountPath: /var/lib/istio/data
        name: istio-data
      - mountPath: /etc/istio/proxy
        name: istio-envoy
      - mountPath: /var/run/secrets/tokens
        name: istio-token
      - mountPath: /etc/istio/pod
        name: istio-podinfo
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-lv847
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    initContainers:
    - env:
      - name: NSM_LOG_LEVEL
        value: TRACE
      - name: SPIFFE_ENDPOINT_SOCKET
        value: unix:///run/spire/sockets/agent.sock
      - name: NSM_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: NSM_NETWORK_SERVICES
        value: kernel://my-vl3-network/nsm-1?dnsName=helloworld
      image: ghcr.io/networkservicemesh/cmd-nsc-init:v1.7.0-rc.2
      imagePullPolicy: IfNotPresent
      name: cmd-nsc-init
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /run/spire/sockets
        name: spire-agent-socket
        readOnly: true
      - mountPath: /var/lib/networkservicemesh
        name: nsm-socket
        readOnly: true
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-lv847
        readOnly: true
    - args:
      - istio-iptables
      - -p
      - "15001"
      - -z
      - "15006"
      - -u
      - "1337"
      - -m
      - REDIRECT
      - -i
      - '*'
      - -x
      - ""
      - -b
      - '*'
      - -d
      - 15090,15021,15020
      - --log_output_level=default:info
      image: docker.io/istio/proxyv2:1.16.0
      imagePullPolicy: IfNotPresent
      name: istio-init
      resources:
        limits:
          cpu: "2"
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
          - NET_ADMIN
          - NET_RAW
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: false
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-lv847
        readOnly: true
    nodeName: kind-1-control-plane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - emptyDir: {}
      name: workload-socket
    - emptyDir: {}
      name: credential-socket
    - emptyDir: {}
      name: workload-certs
    - emptyDir:
        medium: Memory
      name: istio-envoy
    - emptyDir: {}
      name: istio-data
    - downwardAPI:
        defaultMode: 420
        items:
        - fieldRef:
            apiVersion: v1
            fieldPath: metadata.labels
          path: labels
        - fieldRef:
            apiVersion: v1
            fieldPath: metadata.annotations
          path: annotations
      name: istio-podinfo
    - name: istio-token
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            audience: istio-ca
            expirationSeconds: 43200
            path: istio-token
    - configMap:
        defaultMode: 420
        name: istio-ca-root-cert
      name: istiod-ca-cert
    - hostPath:
        path: /run/spire/sockets
        type: Directory
      name: spire-agent-socket
    - hostPath:
        path: /var/lib/networkservicemesh
        type: Directory
      name: nsm-socket
    - name: kube-api-access-lv847
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-12-23T13:30:41Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-12-23T13:31:27Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-12-23T13:31:27Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-12-23T13:30:17Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://e3ed5d5befed7692db2dc0e047dae9a7808ffcdbbd3ab3238c2cfc68e45b94dd
      image: ghcr.io/networkservicemesh/cmd-nsc:v1.7.0-rc.2
      imageID: ghcr.io/networkservicemesh/cmd-nsc@sha256:28bad4c7957cf62fc6637b5908904fe24768f24d24e6516c5e56209ab3a5b111
      lastState: {}
      name: cmd-nsc
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-12-23T13:31:25Z"
    - containerID: containerd://43b17952242d31f04490b74e4a67292ede343a038981d50c839d507c5af68f47
      image: docker.io/istio/examples-helloworld-v1:latest
      imageID: docker.io/istio/examples-helloworld-v1@sha256:c671702b11cbcda103720c2bd3e81a4211012bfef085b7326bb7fbfd8cea4a94
      lastState: {}
      name: helloworld
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-12-23T13:31:25Z"
    - containerID: containerd://27112e89fde87ebe3606e192f5b09c072b19368dd94623c62cdaa027ecc71ce4
      image: docker.io/istio/proxyv2:1.16.0
      imageID: docker.io/istio/proxyv2@sha256:f6f97fa4fb77a3cbe1e3eca0fa46bd462ad6b284c129cf57bf91575c4fb50cf9
      lastState: {}
      name: istio-proxy
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-12-23T13:31:26Z"
    hostIP: 172.18.0.2
    initContainerStatuses:
    - containerID: containerd://017304f20543289dd3ada4909023b5a181bd5659a59795626e25de0c036490a6
      image: ghcr.io/networkservicemesh/cmd-nsc-init:v1.7.0-rc.2
      imageID: ghcr.io/networkservicemesh/cmd-nsc-init@sha256:abc32416a4667f54d1bd8b2891d2d08d2fbce612211214d763c7301760555b52
      lastState: {}
      name: cmd-nsc-init
      ready: true
      restartCount: 0
      state:
        terminated:
          containerID: containerd://017304f20543289dd3ada4909023b5a181bd5659a59795626e25de0c036490a6
          exitCode: 0
          finishedAt: "2022-12-23T13:30:26Z"
          reason: Completed
          startedAt: "2022-12-23T13:30:18Z"
    - containerID: containerd://9d2edfb70d84d1bb9f4437b9cebd79933fe4ddfe4e6e08f3360e3dcb9f8d3660
      image: docker.io/istio/proxyv2:1.16.0
      imageID: docker.io/istio/proxyv2@sha256:f6f97fa4fb77a3cbe1e3eca0fa46bd462ad6b284c129cf57bf91575c4fb50cf9
      lastState: {}
      name: istio-init
      ready: true
      restartCount: 0
      state:
        terminated:
          containerID: containerd://9d2edfb70d84d1bb9f4437b9cebd79933fe4ddfe4e6e08f3360e3dcb9f8d3660
          exitCode: 0
          finishedAt: "2022-12-23T13:30:39Z"
          reason: Completed
          startedAt: "2022-12-23T13:30:39Z"
    phase: Running
    podIP: 10.244.0.16
    podIPs:
    - ip: 10.244.0.16
    qosClass: Burstable
    startTime: "2022-12-23T13:30:17Z"
kind: PodList
metadata:
  resourceVersion: "3083"
