---
apiVersion: v1
items:
- metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"helloworld","service":"helloworld"},"name":"helloworld","namespace":"sample"},"spec":{"ports":[{"name":"http","port":5000},{"name":"http80","port":80}],"selector":{"app":"helloworld"}}}
    creationTimestamp: "2022-12-23T13:30:17Z"
    labels:
      app: helloworld
      service: helloworld
    name: helloworld
    namespace: sample
    resourceVersion: "2015"
    uid: e5fa0541-cb7a-4757-9186-a81003d3b165
  spec:
    clusterIP: 10.96.62.193
    clusterIPs:
    - 10.96.62.193
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
    - name: http80
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: helloworld
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: ServiceList
metadata:
  resourceVersion: "3083"
