---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=648da5a92eea2144c1ee2395a1ceea6ffd20efd9
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=648da5a92eea2144c1ee2395a1ceea6ffd20efd9

resources:
- namespace.yaml

patchesStrategicMerge:
- nse-patch.yaml
